// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Adds one row's word to the custom dictionary (roman = `record.tl`,
 * hanji = `record.text`) unless the dictionary already holds that word —
 * the same Hanji with the same canonical TL, however its roman is spelled.
 * What happens to the row after depends on its kind:
 * - a learned phrase is then forgotten as `DeleteLearningRecord` forgets it
 * (a row already gone is not a failure): the custom word offers the whole
 * phrase from then on, as the learned phrase did, so nothing is lost;
 * - a word-frequency row stays as it is: it keeps weighting the word it
 * counts.
 * Refused as `SaveCustomEntry` is (FULL, or UNSEARCHABLE for a TL that
 * derives no search key), and a refused add keeps the row. A row whose
 * `can_add_to_custom_dictionary` the engine would answer false (an
 * association, no Hanji, a one-syllable TL) is `FAIL_INVARIANT`: a custom
 * word overrides its toneless key in continuous input, so one syllable is
 * left to a deliberate custom-word entry.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.AddLearningRecordToCustomDictionary}
 */
@com.google.protobuf.Generated
public  final class AddLearningRecordToCustomDictionary extends
    com.google.protobuf.GeneratedMessageLite<
        AddLearningRecordToCustomDictionary, AddLearningRecordToCustomDictionary.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.AddLearningRecordToCustomDictionary)
    AddLearningRecordToCustomDictionaryOrBuilder {
  private AddLearningRecordToCustomDictionary() {
  }
  private int bitField0_;
  public static final int RECORD_FIELD_NUMBER = 1;
  private com.siansiansu.taigikeyboard.engine.proto.LearningRecord record_;
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  @java.lang.Override
  public boolean hasRecord() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecord() {
    return record_ == null ? com.siansiansu.taigikeyboard.engine.proto.LearningRecord.getDefaultInstance() : record_;
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  private void setRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
    java.util.Objects.requireNonNull(value);
    record_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
    java.util.Objects.requireNonNull(value);
    if (record_ != null &&
        record_ != com.siansiansu.taigikeyboard.engine.proto.LearningRecord.getDefaultInstance()) {
      record_ =
        com.siansiansu.taigikeyboard.engine.proto.LearningRecord.newBuilder(record_).mergeFrom(value).buildPartial();
    } else {
      record_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  private void clearRecord() {
    record_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Adds one row's word to the custom dictionary (roman = `record.tl`,
   * hanji = `record.text`) unless the dictionary already holds that word —
   * the same Hanji with the same canonical TL, however its roman is spelled.
   * What happens to the row after depends on its kind:
   * - a learned phrase is then forgotten as `DeleteLearningRecord` forgets it
   * (a row already gone is not a failure): the custom word offers the whole
   * phrase from then on, as the learned phrase did, so nothing is lost;
   * - a word-frequency row stays as it is: it keeps weighting the word it
   * counts.
   * Refused as `SaveCustomEntry` is (FULL, or UNSEARCHABLE for a TL that
   * derives no search key), and a refused add keeps the row. A row whose
   * `can_add_to_custom_dictionary` the engine would answer false (an
   * association, no Hanji, a one-syllable TL) is `FAIL_INVARIANT`: a custom
   * word overrides its toneless key in continuous input, so one syllable is
   * left to a deliberate custom-word entry.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.AddLearningRecordToCustomDictionary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.AddLearningRecordToCustomDictionary)
      com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionaryOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    @java.lang.Override
    public boolean hasRecord() {
      return instance.hasRecord();
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecord() {
      return instance.getRecord();
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder setRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
      copyOnWrite();
      instance.setRecord(value);
      return this;
      }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder setRecord(
        com.siansiansu.taigikeyboard.engine.proto.LearningRecord.Builder builderForValue) {
      copyOnWrite();
      instance.setRecord(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder mergeRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
      copyOnWrite();
      instance.mergeRecord(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder clearRecord() {  copyOnWrite();
      instance.clearRecord();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.AddLearningRecordToCustomDictionary)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "record_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.AddLearningRecordToCustomDictionary)
  private static final com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary DEFAULT_INSTANCE;
  static {
    AddLearningRecordToCustomDictionary defaultInstance = new AddLearningRecordToCustomDictionary();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AddLearningRecordToCustomDictionary.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AddLearningRecordToCustomDictionary> PARSER;

  public static com.google.protobuf.Parser<AddLearningRecordToCustomDictionary> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
