// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface AddLearningRecordToCustomDictionaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.AddLearningRecordToCustomDictionary)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   * @return Whether the record field is set.
   */
  boolean hasRecord();
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   * @return The record.
   */
  com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecord();
}
