// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: envelope.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * 2026-09-01 added `candidate_display_mode`: Romanization Only cells hide the hanji, so
 * rows that differ only in hanji (homophones 食/𤆬 tsia̍h) become visible
 * duplicates that only the engine can collapse consistently for four
 * platforms. Set on the BASE config (every request) — composing AND nextword
 * read it; the other request families ignore it. Platforms keep sending the
 * derived `is_hanji_first` (and, on mobile, `output_both_scripts`; the
 * desktop sends only the swap) — both `false` under Romanization Only — so
 * spacing / recording semantics need no new reader.
 *
 * 2026-09-20 added `hyphenless_roman` (No Hyphens, USER): the rendered
 * romanization drops the inter-syllable `-` and writes the neutral-tone marker `--`
 * as `·` U+00B7 (`tâi-uân` → `tâiuân`, `hōo--guá` → `hōo·guá`). Rendering
 * only — `phonetics::api::hyphenless_display` is applied to the candidate
 * `roman` (`composing::requests`), the prediction `text`
 * (`nextword::filter`) and the engine-synthesised compound joiner
 * (`composing::api::nailed_prefix`); identity fields (`display_text`,
 * `canonical_tl`, `tl`) and user-typed text keep their hyphens. The engine
 * applies it only off the TPS layout (`AppConfig::renders_hyphenless`): the
 * platform re-splits `roman` on `-` for bopomofo.
 *
 * 2026-09-22 added `force_lowercase_nasal_marker` (ⁿ becomes ᴺ in capitals OFF, USER): the
 * POJ nasal marker is always `ⁿ` U+207F, never `ᴺ` U+1D3A (Caps Lock
 * `SIANN5` → `SIÂⁿ`). Inverted so the proto default keeps PR #102 (the
 * marker follows the preceding letter's case). Rendering only
 * (`phonetics::case_transform::apply_nasal_marker_case`, §53); identity
 * keys already fold both glyphs to `nn`.
 *
 * 2026-09-30 (R6) `input_mode` accepts `"tps"` as a real mode, and
 * `tps_or_maps_to_er` carries the TPS or→er dialect choice (the same flag
 * `TlNumericToTps` / `TlDisplayToTps` take as `or_maps_to_er`). Under
 * `"tps"` the engine composes with the TL tables and applies the TPS fold
 * itself (`AppConfig::renders_hanji_first` / `renders_hyphenless` in
 * `engine/protos/src/lib.rs`), so `is_hanji_first` and
 * `hyphenless_roman` are the Candidate-Display-projected stored values
 * WITHOUT the TPS fold. A platform may still send the pre-R6 wire (`"tl"`
 * plus the TPS-folded swap / hyphenless) — composing renders both
 * identically. Nextword's empty-romanization drop and Enter skip read the
 * swap as sent, not folded; today every platform sends nextword the stored
 * swap, so moving to `"tps"` changes nothing there.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.AppConfig}
 */
@com.google.protobuf.Generated
public  final class AppConfig extends
    com.google.protobuf.GeneratedMessageLite<
        AppConfig, AppConfig.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.AppConfig)
    AppConfigOrBuilder {
  private AppConfig() {
    inputMode_ = "";
  }
  public static final int INPUT_MODE_FIELD_NUMBER = 2;
  private java.lang.String inputMode_;
  /**
   * <pre>
   * "tl" | "poj" | "tps" | "english".
   * </pre>
   *
   * <code>string input_mode = 2;</code>
   * @return The inputMode.
   */
  @java.lang.Override
  public java.lang.String getInputMode() {
    return inputMode_;
  }
  /**
   * <pre>
   * "tl" | "poj" | "tps" | "english".
   * </pre>
   *
   * <code>string input_mode = 2;</code>
   * @return The bytes for inputMode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputModeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(inputMode_);
  }
  /**
   * <pre>
   * "tl" | "poj" | "tps" | "english".
   * </pre>
   *
   * <code>string input_mode = 2;</code>
   * @param value The inputMode to set.
   */
  private void setInputMode(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    inputMode_ = value;
  }
  /**
   * <pre>
   * "tl" | "poj" | "tps" | "english".
   * </pre>
   *
   * <code>string input_mode = 2;</code>
   */
  private void clearInputMode() {

    inputMode_ = getDefaultInstance().getInputMode();
  }
  /**
   * <pre>
   * "tl" | "poj" | "tps" | "english".
   * </pre>
   *
   * <code>string input_mode = 2;</code>
   * @param value The bytes for inputMode to set.
   */
  private void setInputModeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    inputMode_ = value.toStringUtf8();

  }

  public static final int OO_DOUBLETAP_ENABLED_FIELD_NUMBER = 3;
  private boolean ooDoubletapEnabled_;
  /**
   * <code>bool oo_doubletap_enabled = 3;</code>
   * @return The ooDoubletapEnabled.
   */
  @java.lang.Override
  public boolean getOoDoubletapEnabled() {
    return ooDoubletapEnabled_;
  }
  /**
   * <code>bool oo_doubletap_enabled = 3;</code>
   * @param value The ooDoubletapEnabled to set.
   */
  private void setOoDoubletapEnabled(boolean value) {

    ooDoubletapEnabled_ = value;
  }
  /**
   * <code>bool oo_doubletap_enabled = 3;</code>
   */
  private void clearOoDoubletapEnabled() {

    ooDoubletapEnabled_ = false;
  }

  public static final int NN_DOUBLETAP_ENABLED_FIELD_NUMBER = 4;
  private boolean nnDoubletapEnabled_;
  /**
   * <code>bool nn_doubletap_enabled = 4;</code>
   * @return The nnDoubletapEnabled.
   */
  @java.lang.Override
  public boolean getNnDoubletapEnabled() {
    return nnDoubletapEnabled_;
  }
  /**
   * <code>bool nn_doubletap_enabled = 4;</code>
   * @param value The nnDoubletapEnabled to set.
   */
  private void setNnDoubletapEnabled(boolean value) {

    nnDoubletapEnabled_ = value;
  }
  /**
   * <code>bool nn_doubletap_enabled = 4;</code>
   */
  private void clearNnDoubletapEnabled() {

    nnDoubletapEnabled_ = false;
  }

  public static final int IS_HANJI_FIRST_FIELD_NUMBER = 5;
  private boolean isHanjiFirst_;
  /**
   * <pre>
   * Candidate-Display-projected Hanji-first swap, without the TPS fold.
   * </pre>
   *
   * <code>bool is_hanji_first = 5;</code>
   * @return The isHanjiFirst.
   */
  @java.lang.Override
  public boolean getIsHanjiFirst() {
    return isHanjiFirst_;
  }
  /**
   * <pre>
   * Candidate-Display-projected Hanji-first swap, without the TPS fold.
   * </pre>
   *
   * <code>bool is_hanji_first = 5;</code>
   * @param value The isHanjiFirst to set.
   */
  private void setIsHanjiFirst(boolean value) {

    isHanjiFirst_ = value;
  }
  /**
   * <pre>
   * Candidate-Display-projected Hanji-first swap, without the TPS fold.
   * </pre>
   *
   * <code>bool is_hanji_first = 5;</code>
   */
  private void clearIsHanjiFirst() {

    isHanjiFirst_ = false;
  }

  public static final int PLATFORM_ID_FIELD_NUMBER = 7;
  private int platformId_;
  /**
   * <code>.taigi.engine.Platform platform_id = 7;</code>
   * @return The enum numeric value on the wire for platformId.
   */
  @java.lang.Override
  public int getPlatformIdValue() {
    return platformId_;
  }
  /**
   * <code>.taigi.engine.Platform platform_id = 7;</code>
   * @return The platformId.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.Platform getPlatformId() {
    com.siansiansu.taigikeyboard.engine.proto.Platform result = com.siansiansu.taigikeyboard.engine.proto.Platform.forNumber(platformId_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.Platform.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.Platform platform_id = 7;</code>
   * @param value The enum numeric value on the wire for platformId to set.
   */
  private void setPlatformIdValue(int value) {
      platformId_ = value;
  }
  /**
   * <code>.taigi.engine.Platform platform_id = 7;</code>
   * @param value The platformId to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setPlatformId(com.siansiansu.taigikeyboard.engine.proto.Platform value) {
    platformId_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.Platform platform_id = 7;</code>
   */
  private void clearPlatformId() {

    platformId_ = 0;
  }

  public static final int OUTPUT_BOTH_SCRIPTS_FIELD_NUMBER = 8;
  private boolean outputBothScripts_;
  /**
   * <code>bool output_both_scripts = 8;</code>
   * @return The outputBothScripts.
   */
  @java.lang.Override
  public boolean getOutputBothScripts() {
    return outputBothScripts_;
  }
  /**
   * <code>bool output_both_scripts = 8;</code>
   * @param value The outputBothScripts to set.
   */
  private void setOutputBothScripts(boolean value) {

    outputBothScripts_ = value;
  }
  /**
   * <code>bool output_both_scripts = 8;</code>
   */
  private void clearOutputBothScripts() {

    outputBothScripts_ = false;
  }

  public static final int CANDIDATE_DISPLAY_MODE_FIELD_NUMBER = 9;
  private int candidateDisplayMode_;
  /**
   * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
   * @return The enum numeric value on the wire for candidateDisplayMode.
   */
  @java.lang.Override
  public int getCandidateDisplayModeValue() {
    return candidateDisplayMode_;
  }
  /**
   * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
   * @return The candidateDisplayMode.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.CandidateDisplayMode getCandidateDisplayMode() {
    com.siansiansu.taigikeyboard.engine.proto.CandidateDisplayMode result = com.siansiansu.taigikeyboard.engine.proto.CandidateDisplayMode.forNumber(candidateDisplayMode_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.CandidateDisplayMode.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
   * @param value The enum numeric value on the wire for candidateDisplayMode to set.
   */
  private void setCandidateDisplayModeValue(int value) {
      candidateDisplayMode_ = value;
  }
  /**
   * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
   * @param value The candidateDisplayMode to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setCandidateDisplayMode(com.siansiansu.taigikeyboard.engine.proto.CandidateDisplayMode value) {
    candidateDisplayMode_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
   */
  private void clearCandidateDisplayMode() {

    candidateDisplayMode_ = 0;
  }

  public static final int HYPHENLESS_ROMAN_FIELD_NUMBER = 10;
  private boolean hyphenlessRoman_;
  /**
   * <pre>
   * No Hyphens as stored, without the TPS fold.
   * </pre>
   *
   * <code>bool hyphenless_roman = 10;</code>
   * @return The hyphenlessRoman.
   */
  @java.lang.Override
  public boolean getHyphenlessRoman() {
    return hyphenlessRoman_;
  }
  /**
   * <pre>
   * No Hyphens as stored, without the TPS fold.
   * </pre>
   *
   * <code>bool hyphenless_roman = 10;</code>
   * @param value The hyphenlessRoman to set.
   */
  private void setHyphenlessRoman(boolean value) {

    hyphenlessRoman_ = value;
  }
  /**
   * <pre>
   * No Hyphens as stored, without the TPS fold.
   * </pre>
   *
   * <code>bool hyphenless_roman = 10;</code>
   */
  private void clearHyphenlessRoman() {

    hyphenlessRoman_ = false;
  }

  public static final int FORCE_LOWERCASE_NASAL_MARKER_FIELD_NUMBER = 11;
  private boolean forceLowercaseNasalMarker_;
  /**
   * <code>bool force_lowercase_nasal_marker = 11;</code>
   * @return The forceLowercaseNasalMarker.
   */
  @java.lang.Override
  public boolean getForceLowercaseNasalMarker() {
    return forceLowercaseNasalMarker_;
  }
  /**
   * <code>bool force_lowercase_nasal_marker = 11;</code>
   * @param value The forceLowercaseNasalMarker to set.
   */
  private void setForceLowercaseNasalMarker(boolean value) {

    forceLowercaseNasalMarker_ = value;
  }
  /**
   * <code>bool force_lowercase_nasal_marker = 11;</code>
   */
  private void clearForceLowercaseNasalMarker() {

    forceLowercaseNasalMarker_ = false;
  }

  public static final int TPS_OR_MAPS_TO_ER_FIELD_NUMBER = 12;
  private boolean tpsOrMapsToEr_;
  /**
   * <pre>
   * TPS or→er dialect switch; no engine reader yet.
   * </pre>
   *
   * <code>bool tps_or_maps_to_er = 12;</code>
   * @return The tpsOrMapsToEr.
   */
  @java.lang.Override
  public boolean getTpsOrMapsToEr() {
    return tpsOrMapsToEr_;
  }
  /**
   * <pre>
   * TPS or→er dialect switch; no engine reader yet.
   * </pre>
   *
   * <code>bool tps_or_maps_to_er = 12;</code>
   * @param value The tpsOrMapsToEr to set.
   */
  private void setTpsOrMapsToEr(boolean value) {

    tpsOrMapsToEr_ = value;
  }
  /**
   * <pre>
   * TPS or→er dialect switch; no engine reader yet.
   * </pre>
   *
   * <code>bool tps_or_maps_to_er = 12;</code>
   */
  private void clearTpsOrMapsToEr() {

    tpsOrMapsToEr_ = false;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.AppConfig prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * 2026-09-01 added `candidate_display_mode`: Romanization Only cells hide the hanji, so
   * rows that differ only in hanji (homophones 食/𤆬 tsia̍h) become visible
   * duplicates that only the engine can collapse consistently for four
   * platforms. Set on the BASE config (every request) — composing AND nextword
   * read it; the other request families ignore it. Platforms keep sending the
   * derived `is_hanji_first` (and, on mobile, `output_both_scripts`; the
   * desktop sends only the swap) — both `false` under Romanization Only — so
   * spacing / recording semantics need no new reader.
   *
   * 2026-09-20 added `hyphenless_roman` (No Hyphens, USER): the rendered
   * romanization drops the inter-syllable `-` and writes the neutral-tone marker `--`
   * as `·` U+00B7 (`tâi-uân` → `tâiuân`, `hōo--guá` → `hōo·guá`). Rendering
   * only — `phonetics::api::hyphenless_display` is applied to the candidate
   * `roman` (`composing::requests`), the prediction `text`
   * (`nextword::filter`) and the engine-synthesised compound joiner
   * (`composing::api::nailed_prefix`); identity fields (`display_text`,
   * `canonical_tl`, `tl`) and user-typed text keep their hyphens. The engine
   * applies it only off the TPS layout (`AppConfig::renders_hyphenless`): the
   * platform re-splits `roman` on `-` for bopomofo.
   *
   * 2026-09-22 added `force_lowercase_nasal_marker` (ⁿ becomes ᴺ in capitals OFF, USER): the
   * POJ nasal marker is always `ⁿ` U+207F, never `ᴺ` U+1D3A (Caps Lock
   * `SIANN5` → `SIÂⁿ`). Inverted so the proto default keeps PR #102 (the
   * marker follows the preceding letter's case). Rendering only
   * (`phonetics::case_transform::apply_nasal_marker_case`, §53); identity
   * keys already fold both glyphs to `nn`.
   *
   * 2026-09-30 (R6) `input_mode` accepts `"tps"` as a real mode, and
   * `tps_or_maps_to_er` carries the TPS or→er dialect choice (the same flag
   * `TlNumericToTps` / `TlDisplayToTps` take as `or_maps_to_er`). Under
   * `"tps"` the engine composes with the TL tables and applies the TPS fold
   * itself (`AppConfig::renders_hanji_first` / `renders_hyphenless` in
   * `engine/protos/src/lib.rs`), so `is_hanji_first` and
   * `hyphenless_roman` are the Candidate-Display-projected stored values
   * WITHOUT the TPS fold. A platform may still send the pre-R6 wire (`"tl"`
   * plus the TPS-folded swap / hyphenless) — composing renders both
   * identically. Nextword's empty-romanization drop and Enter skip read the
   * swap as sent, not folded; today every platform sends nextword the stored
   * swap, so moving to `"tps"` changes nothing there.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.AppConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.AppConfig, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.AppConfig)
      com.siansiansu.taigikeyboard.engine.proto.AppConfigOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.AppConfig.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * "tl" | "poj" | "tps" | "english".
     * </pre>
     *
     * <code>string input_mode = 2;</code>
     * @return The inputMode.
     */
    @java.lang.Override
    public java.lang.String getInputMode() {
      return instance.getInputMode();
    }
    /**
     * <pre>
     * "tl" | "poj" | "tps" | "english".
     * </pre>
     *
     * <code>string input_mode = 2;</code>
     * @return The bytes for inputMode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInputModeBytes() {
      return instance.getInputModeBytes();
    }
    /**
     * <pre>
     * "tl" | "poj" | "tps" | "english".
     * </pre>
     *
     * <code>string input_mode = 2;</code>
     * @param value The inputMode to set.
     * @return This builder for chaining.
     */
    public Builder setInputMode(
        java.lang.String value) {
      copyOnWrite();
      instance.setInputMode(value);
      return this;
    }
    /**
     * <pre>
     * "tl" | "poj" | "tps" | "english".
     * </pre>
     *
     * <code>string input_mode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInputMode() {
      copyOnWrite();
      instance.clearInputMode();
      return this;
    }
    /**
     * <pre>
     * "tl" | "poj" | "tps" | "english".
     * </pre>
     *
     * <code>string input_mode = 2;</code>
     * @param value The bytes for inputMode to set.
     * @return This builder for chaining.
     */
    public Builder setInputModeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setInputModeBytes(value);
      return this;
    }

    /**
     * <code>bool oo_doubletap_enabled = 3;</code>
     * @return The ooDoubletapEnabled.
     */
    @java.lang.Override
    public boolean getOoDoubletapEnabled() {
      return instance.getOoDoubletapEnabled();
    }
    /**
     * <code>bool oo_doubletap_enabled = 3;</code>
     * @param value The ooDoubletapEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setOoDoubletapEnabled(boolean value) {
      copyOnWrite();
      instance.setOoDoubletapEnabled(value);
      return this;
    }
    /**
     * <code>bool oo_doubletap_enabled = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOoDoubletapEnabled() {
      copyOnWrite();
      instance.clearOoDoubletapEnabled();
      return this;
    }

    /**
     * <code>bool nn_doubletap_enabled = 4;</code>
     * @return The nnDoubletapEnabled.
     */
    @java.lang.Override
    public boolean getNnDoubletapEnabled() {
      return instance.getNnDoubletapEnabled();
    }
    /**
     * <code>bool nn_doubletap_enabled = 4;</code>
     * @param value The nnDoubletapEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setNnDoubletapEnabled(boolean value) {
      copyOnWrite();
      instance.setNnDoubletapEnabled(value);
      return this;
    }
    /**
     * <code>bool nn_doubletap_enabled = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNnDoubletapEnabled() {
      copyOnWrite();
      instance.clearNnDoubletapEnabled();
      return this;
    }

    /**
     * <pre>
     * Candidate-Display-projected Hanji-first swap, without the TPS fold.
     * </pre>
     *
     * <code>bool is_hanji_first = 5;</code>
     * @return The isHanjiFirst.
     */
    @java.lang.Override
    public boolean getIsHanjiFirst() {
      return instance.getIsHanjiFirst();
    }
    /**
     * <pre>
     * Candidate-Display-projected Hanji-first swap, without the TPS fold.
     * </pre>
     *
     * <code>bool is_hanji_first = 5;</code>
     * @param value The isHanjiFirst to set.
     * @return This builder for chaining.
     */
    public Builder setIsHanjiFirst(boolean value) {
      copyOnWrite();
      instance.setIsHanjiFirst(value);
      return this;
    }
    /**
     * <pre>
     * Candidate-Display-projected Hanji-first swap, without the TPS fold.
     * </pre>
     *
     * <code>bool is_hanji_first = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsHanjiFirst() {
      copyOnWrite();
      instance.clearIsHanjiFirst();
      return this;
    }

    /**
     * <code>.taigi.engine.Platform platform_id = 7;</code>
     * @return The enum numeric value on the wire for platformId.
     */
    @java.lang.Override
    public int getPlatformIdValue() {
      return instance.getPlatformIdValue();
    }
    /**
     * <code>.taigi.engine.Platform platform_id = 7;</code>
     * @param value The platformId to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setPlatformIdValue(int value) {
      copyOnWrite();
      instance.setPlatformIdValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.Platform platform_id = 7;</code>
     * @return The platformId.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.Platform getPlatformId() {
      return instance.getPlatformId();
    }
    /**
     * <code>.taigi.engine.Platform platform_id = 7;</code>
     * @param value The enum numeric value on the wire for platformId to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformId(com.siansiansu.taigikeyboard.engine.proto.Platform value) {
      copyOnWrite();
      instance.setPlatformId(value);
      return this;
    }
    /**
     * <code>.taigi.engine.Platform platform_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatformId() {
      copyOnWrite();
      instance.clearPlatformId();
      return this;
    }

    /**
     * <code>bool output_both_scripts = 8;</code>
     * @return The outputBothScripts.
     */
    @java.lang.Override
    public boolean getOutputBothScripts() {
      return instance.getOutputBothScripts();
    }
    /**
     * <code>bool output_both_scripts = 8;</code>
     * @param value The outputBothScripts to set.
     * @return This builder for chaining.
     */
    public Builder setOutputBothScripts(boolean value) {
      copyOnWrite();
      instance.setOutputBothScripts(value);
      return this;
    }
    /**
     * <code>bool output_both_scripts = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutputBothScripts() {
      copyOnWrite();
      instance.clearOutputBothScripts();
      return this;
    }

    /**
     * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
     * @return The enum numeric value on the wire for candidateDisplayMode.
     */
    @java.lang.Override
    public int getCandidateDisplayModeValue() {
      return instance.getCandidateDisplayModeValue();
    }
    /**
     * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
     * @param value The candidateDisplayMode to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setCandidateDisplayModeValue(int value) {
      copyOnWrite();
      instance.setCandidateDisplayModeValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
     * @return The candidateDisplayMode.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.CandidateDisplayMode getCandidateDisplayMode() {
      return instance.getCandidateDisplayMode();
    }
    /**
     * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
     * @param value The enum numeric value on the wire for candidateDisplayMode to set.
     * @return This builder for chaining.
     */
    public Builder setCandidateDisplayMode(com.siansiansu.taigikeyboard.engine.proto.CandidateDisplayMode value) {
      copyOnWrite();
      instance.setCandidateDisplayMode(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CandidateDisplayMode candidate_display_mode = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearCandidateDisplayMode() {
      copyOnWrite();
      instance.clearCandidateDisplayMode();
      return this;
    }

    /**
     * <pre>
     * No Hyphens as stored, without the TPS fold.
     * </pre>
     *
     * <code>bool hyphenless_roman = 10;</code>
     * @return The hyphenlessRoman.
     */
    @java.lang.Override
    public boolean getHyphenlessRoman() {
      return instance.getHyphenlessRoman();
    }
    /**
     * <pre>
     * No Hyphens as stored, without the TPS fold.
     * </pre>
     *
     * <code>bool hyphenless_roman = 10;</code>
     * @param value The hyphenlessRoman to set.
     * @return This builder for chaining.
     */
    public Builder setHyphenlessRoman(boolean value) {
      copyOnWrite();
      instance.setHyphenlessRoman(value);
      return this;
    }
    /**
     * <pre>
     * No Hyphens as stored, without the TPS fold.
     * </pre>
     *
     * <code>bool hyphenless_roman = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearHyphenlessRoman() {
      copyOnWrite();
      instance.clearHyphenlessRoman();
      return this;
    }

    /**
     * <code>bool force_lowercase_nasal_marker = 11;</code>
     * @return The forceLowercaseNasalMarker.
     */
    @java.lang.Override
    public boolean getForceLowercaseNasalMarker() {
      return instance.getForceLowercaseNasalMarker();
    }
    /**
     * <code>bool force_lowercase_nasal_marker = 11;</code>
     * @param value The forceLowercaseNasalMarker to set.
     * @return This builder for chaining.
     */
    public Builder setForceLowercaseNasalMarker(boolean value) {
      copyOnWrite();
      instance.setForceLowercaseNasalMarker(value);
      return this;
    }
    /**
     * <code>bool force_lowercase_nasal_marker = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearForceLowercaseNasalMarker() {
      copyOnWrite();
      instance.clearForceLowercaseNasalMarker();
      return this;
    }

    /**
     * <pre>
     * TPS or→er dialect switch; no engine reader yet.
     * </pre>
     *
     * <code>bool tps_or_maps_to_er = 12;</code>
     * @return The tpsOrMapsToEr.
     */
    @java.lang.Override
    public boolean getTpsOrMapsToEr() {
      return instance.getTpsOrMapsToEr();
    }
    /**
     * <pre>
     * TPS or→er dialect switch; no engine reader yet.
     * </pre>
     *
     * <code>bool tps_or_maps_to_er = 12;</code>
     * @param value The tpsOrMapsToEr to set.
     * @return This builder for chaining.
     */
    public Builder setTpsOrMapsToEr(boolean value) {
      copyOnWrite();
      instance.setTpsOrMapsToEr(value);
      return this;
    }
    /**
     * <pre>
     * TPS or→er dialect switch; no engine reader yet.
     * </pre>
     *
     * <code>bool tps_or_maps_to_er = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearTpsOrMapsToEr() {
      copyOnWrite();
      instance.clearTpsOrMapsToEr();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.AppConfig)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.AppConfig();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "inputMode_",
            "ooDoubletapEnabled_",
            "nnDoubletapEnabled_",
            "isHanjiFirst_",
            "platformId_",
            "outputBothScripts_",
            "candidateDisplayMode_",
            "hyphenlessRoman_",
            "forceLowercaseNasalMarker_",
            "tpsOrMapsToEr_",
          };
          java.lang.String info =
              "\u0000\n\u0000\u0000\u0002\f\n\u0000\u0000\u0000\u0002\u0208\u0003\u0007\u0004\u0007" +
              "\u0005\u0007\u0007\f\b\u0007\t\f\n\u0007\u000b\u0007\f\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.AppConfig> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.AppConfig.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.AppConfig>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.AppConfig)
  private static final com.siansiansu.taigikeyboard.engine.proto.AppConfig DEFAULT_INSTANCE;
  static {
    AppConfig defaultInstance = new AppConfig();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AppConfig.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.AppConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AppConfig> PARSER;

  public static com.google.protobuf.Parser<AppConfig> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
