// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface AssocLookupRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.AssocLookupRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * The committed word, whole; the lexicon picks the key (word key
   * `previous_word&#92;u{1}previous_tl`, else the last character).
   * </pre>
   *
   * <code>string previous_word = 1;</code>
   * @return The previousWord.
   */
  java.lang.String getPreviousWord();
  /**
   * <pre>
   * The committed word, whole; the lexicon picks the key (word key
   * `previous_word&#92;u{1}previous_tl`, else the last character).
   * </pre>
   *
   * <code>string previous_word = 1;</code>
   * @return The bytes for previousWord.
   */
  com.google.protobuf.ByteString
      getPreviousWordBytes();

  /**
   * <code>uint32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   * Source-toggle bitmask filtering bundled bigram entries. Layout matches
   * the low 9 bits of `enabled_sources_bitmask` in `SearchRequest`. Sentinel
   * `u32::MAX` short-circuits the filter (all sources enabled). Plumbed end
   * -to-end since v3.5.6 fix r3173013233 — prior to that, api.rs hardcoded
   * `u32::MAX`, regressing the platform-side filter that used to honor
   * `EnabledDictionaries.associationBitmask()`.
   * </pre>
   *
   * <code>uint32 enabled_sources_bitmask = 3;</code>
   * @return The enabledSourcesBitmask.
   */
  int getEnabledSourcesBitmask();

  /**
   * <pre>
   * The committed word's canonical display TL. Non-empty → the word key is
   * tried first and the character key is the backoff when it yields no row
   * under the mask; empty → character key only (behavioral-invariants §24
   * INVARIANT_NEXTWORD_WORD_KEY_BACKOFF).
   * </pre>
   *
   * <code>string previous_tl = 4;</code>
   * @return The previousTl.
   */
  java.lang.String getPreviousTl();
  /**
   * <pre>
   * The committed word's canonical display TL. Non-empty → the word key is
   * tried first and the character key is the backoff when it yields no row
   * under the mask; empty → character key only (behavioral-invariants §24
   * INVARIANT_NEXTWORD_WORD_KEY_BACKOFF).
   * </pre>
   *
   * <code>string previous_tl = 4;</code>
   * @return The bytes for previousTl.
   */
  com.google.protobuf.ByteString
      getPreviousTlBytes();
}
