// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * v3.5.8 Phase 9.2 — candidate-type discriminator. MOE `VocType`
 * (`VT_HANT` / `VT_TAILO` / `VT_MIXED`) is the cite. Derived in Rust
 * from `DictionaryRecord.hanji` presence + NFKD-normalized Latin-letter
 * detection; see `engine/lexicon/src/continuous/mod.rs::derive_script_kind`.
 *
 * Metadata-only: this field does NOT enter the `CandidateSortKey` tie-break
 * in v3.5.8 (per `docs/releases/v3.5.8/plan.md` § Phase 9 R2 Q3.a — "reserve rank
 * use until real collisions are measured"). It is orthogonal to the
 * existing `form` axis (toneless / numeric / hanji / abbrev).
 *
 * `UNSPECIFIED = 0` is the proto3 default and never emitted by Rust;
 * platforms must treat `UNSPECIFIED` as "unknown carrier — fall back
 * to display-text sniff" rather than as HANT.
 * </pre>
 *
 * Protobuf enum {@code taigi.engine.CandidateScriptKind}
 */
@com.google.protobuf.Generated
public enum CandidateScriptKind
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>CANDIDATE_SCRIPT_KIND_UNSPECIFIED = 0;</code>
   */
  CANDIDATE_SCRIPT_KIND_UNSPECIFIED(0),
  /**
   * <code>CANDIDATE_SCRIPT_KIND_HANT = 1;</code>
   */
  CANDIDATE_SCRIPT_KIND_HANT(1),
  /**
   * <code>CANDIDATE_SCRIPT_KIND_TAILO = 2;</code>
   */
  CANDIDATE_SCRIPT_KIND_TAILO(2),
  /**
   * <code>CANDIDATE_SCRIPT_KIND_MIXED = 3;</code>
   */
  CANDIDATE_SCRIPT_KIND_MIXED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CANDIDATE_SCRIPT_KIND_UNSPECIFIED = 0;</code>
   */
  public static final int CANDIDATE_SCRIPT_KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CANDIDATE_SCRIPT_KIND_HANT = 1;</code>
   */
  public static final int CANDIDATE_SCRIPT_KIND_HANT_VALUE = 1;
  /**
   * <code>CANDIDATE_SCRIPT_KIND_TAILO = 2;</code>
   */
  public static final int CANDIDATE_SCRIPT_KIND_TAILO_VALUE = 2;
  /**
   * <code>CANDIDATE_SCRIPT_KIND_MIXED = 3;</code>
   */
  public static final int CANDIDATE_SCRIPT_KIND_MIXED_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CandidateScriptKind valueOf(int value) {
    return forNumber(value);
  }

  public static CandidateScriptKind forNumber(int value) {
    switch (value) {
      case 0: return CANDIDATE_SCRIPT_KIND_UNSPECIFIED;
      case 1: return CANDIDATE_SCRIPT_KIND_HANT;
      case 2: return CANDIDATE_SCRIPT_KIND_TAILO;
      case 3: return CANDIDATE_SCRIPT_KIND_MIXED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CandidateScriptKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CandidateScriptKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CandidateScriptKind>() {
          @java.lang.Override
          public CandidateScriptKind findValueByNumber(int number) {
            return CandidateScriptKind.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier
      internalGetVerifier() {
    return CandidateScriptKindVerifier.INSTANCE;
  }

  private static final class CandidateScriptKindVerifier implements
       com.google.protobuf.Internal.EnumVerifier {
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new CandidateScriptKindVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return CandidateScriptKind.forNumber(number) != null;
          }
        };

  private final int value;

  private CandidateScriptKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:taigi.engine.CandidateScriptKind)
}
