// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface CommitResolutionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.CommitResolution)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
   * @return The enum numeric value on the wire for outcome.
   */
  int getOutcomeValue();
  /**
   * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
   * @return The outcome.
   */
  com.siansiansu.taigikeyboard.engine.proto.CommitOutcome getOutcome();

  /**
   * <pre>
   * The text this pick wrote into the composition — the segment, not the
   * whole finalized composition. Empty when IGNORED.
   * </pre>
   *
   * <code>string document_text = 2;</code>
   * @return The documentText.
   */
  java.lang.String getDocumentText();
  /**
   * <pre>
   * The text this pick wrote into the composition — the segment, not the
   * whole finalized composition. Empty when IGNORED.
   * </pre>
   *
   * <code>string document_text = 2;</code>
   * @return The bytes for documentText.
   */
  com.google.protobuf.ByteString
      getDocumentTextBytes();

  /**
   * <pre>
   * `document_text` carries romanization (behavioral-invariants §23).
   * </pre>
   *
   * <code>bool wrote_romanization = 3;</code>
   * @return The wroteRomanization.
   */
  boolean getWroteRomanization();

  /**
   * <pre>
   * FINALIZED &amp;&amp; wrote_romanization &amp;&amp; `document_text` does not end in `-`.
   * The platform still ANDs its live Auto-Space setting.
   * </pre>
   *
   * <code>bool earns_auto_space = 4;</code>
   * @return The earnsAutoSpace.
   */
  boolean getEarnsAutoSpace();
}
