// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface CommitContinuousOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.CommitContinuous)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 consumed_bytes = 2;</code>
   * @return The consumedBytes.
   */
  int getConsumedBytes();

  /**
   * <code>uint32 syllable_count = 3;</code>
   * @return The syllableCount.
   */
  int getSyllableCount();

  /**
   * <pre>
   * v3.5.8 Phase 9 Bug 1 (Option A). Canonical dictionary key
   * (`hanji.unwrap_or(roman)`) the engine counts the pick under
   * (`user_frequency.db`) and NextWord learns, so learning stays
   * mode-independent. Empty → the commit is IGNORED.
   * </pre>
   *
   * <code>string canonical_text = 4;</code>
   * @return The canonicalText.
   */
  java.lang.String getCanonicalText();
  /**
   * <pre>
   * v3.5.8 Phase 9 Bug 1 (Option A). Canonical dictionary key
   * (`hanji.unwrap_or(roman)`) the engine counts the pick under
   * (`user_frequency.db`) and NextWord learns, so learning stays
   * mode-independent. Empty → the commit is IGNORED.
   * </pre>
   *
   * <code>string canonical_text = 4;</code>
   * @return The bytes for canonicalText.
   */
  com.google.protobuf.ByteString
      getCanonicalTextBytes();

  /**
   * <pre>
   * v3.6.1 R2 — canonical TL romanization of the committed candidate
   * (`CandidateMessage.canonical_tl`, snapshotted BEFORE the POJ-render /
   * recase passes rewrite `roman`). Becomes the `roman` arg of the
   * NextWord `WordSelected` / `UpdateLastSelectedWord` effects so the
   * learned association `prev_tl` / `next_tl` is the same canonical TL a
   * normal (non-continuous) candidate commit records — fixing the
   * continuous-vs-normal `next_tl` fragmentation (raw typed slice
   * `taigi` vs canonical `tâi-gí`). Wire-absent / empty (legacy callers,
   * the other 12 methods, TPS-OOV hanji-absent candidates with no dict
   * TL) decodes as "" → engine falls back to the raw committed slice
   * (`pending[..consumed_bytes]`), preserving pre-R2 behavior. Identity
   * is the `(hanji, canonical-TL)` pair (Core Principle #7), so this is
   * populated for hanji-present candidates too, NOT only hanji-absent.
   * </pre>
   *
   * <code>string association_tl = 5;</code>
   * @return The associationTl.
   */
  java.lang.String getAssociationTl();
  /**
   * <pre>
   * v3.6.1 R2 — canonical TL romanization of the committed candidate
   * (`CandidateMessage.canonical_tl`, snapshotted BEFORE the POJ-render /
   * recase passes rewrite `roman`). Becomes the `roman` arg of the
   * NextWord `WordSelected` / `UpdateLastSelectedWord` effects so the
   * learned association `prev_tl` / `next_tl` is the same canonical TL a
   * normal (non-continuous) candidate commit records — fixing the
   * continuous-vs-normal `next_tl` fragmentation (raw typed slice
   * `taigi` vs canonical `tâi-gí`). Wire-absent / empty (legacy callers,
   * the other 12 methods, TPS-OOV hanji-absent candidates with no dict
   * TL) decodes as "" → engine falls back to the raw committed slice
   * (`pending[..consumed_bytes]`), preserving pre-R2 behavior. Identity
   * is the `(hanji, canonical-TL)` pair (Core Principle #7), so this is
   * populated for hanji-present candidates too, NOT only hanji-absent.
   * </pre>
   *
   * <code>string association_tl = 5;</code>
   * @return The bytes for associationTl.
   */
  com.google.protobuf.ByteString
      getAssociationTlBytes();

  /**
   * <pre>
   * Learned phrases (§50) — the chosen `CandidateMessage.hanji`, sent
   * whenever the picked candidate carries hanji regardless of which script
   * the document received (identity = the `(Hanji, canonical-TL)` pair, Core
   * Principle #6; a Hanji with Romanization roman cell commits the same candidate). Wire-absent
   * for a hanji-less pick (§34 literal, OOV synth, roman-only custom row)
   * and for legacy callers; a composition with any hanji-less segment is
   * never learned. proto3 `optional` so absent ≠ empty (Codex 2026-09-20
   * F2: hanji is an explicit sidechannel, never inferred from
   * `canonical_text` vs `association_tl`).
   * </pre>
   *
   * <code>optional string hanji = 6;</code>
   * @return Whether the hanji field is set.
   */
  boolean hasHanji();
  /**
   * <pre>
   * Learned phrases (§50) — the chosen `CandidateMessage.hanji`, sent
   * whenever the picked candidate carries hanji regardless of which script
   * the document received (identity = the `(Hanji, canonical-TL)` pair, Core
   * Principle #6; a Hanji with Romanization roman cell commits the same candidate). Wire-absent
   * for a hanji-less pick (§34 literal, OOV synth, roman-only custom row)
   * and for legacy callers; a composition with any hanji-less segment is
   * never learned. proto3 `optional` so absent ≠ empty (Codex 2026-09-20
   * F2: hanji is an explicit sidechannel, never inferred from
   * `canonical_text` vs `association_tl`).
   * </pre>
   *
   * <code>optional string hanji = 6;</code>
   * @return The hanji.
   */
  java.lang.String getHanji();
  /**
   * <pre>
   * Learned phrases (§50) — the chosen `CandidateMessage.hanji`, sent
   * whenever the picked candidate carries hanji regardless of which script
   * the document received (identity = the `(Hanji, canonical-TL)` pair, Core
   * Principle #6; a Hanji with Romanization roman cell commits the same candidate). Wire-absent
   * for a hanji-less pick (§34 literal, OOV synth, roman-only custom row)
   * and for legacy callers; a composition with any hanji-less segment is
   * never learned. proto3 `optional` so absent ≠ empty (Codex 2026-09-20
   * F2: hanji is an explicit sidechannel, never inferred from
   * `canonical_text` vs `association_tl`).
   * </pre>
   *
   * <code>optional string hanji = 6;</code>
   * @return The bytes for hanji.
   */
  com.google.protobuf.ByteString
      getHanjiBytes();

  /**
   * <pre>
   * R5 — engine-owned commit resolution: the engine resolves the document
   * text from `roman`, `hanji` and the request's `AppConfig`
   * (`composing::commit_text`), answers `ComposingResponse.commit`, and —
   * with the user-data stores open — records the pick's usage itself (the
   * platform sends no `RecordUsage` for it). `UNSPECIFIED` (or a script
   * newer than the engine) is IGNORED. On the TPS layout the romanization
   * written renders as Bopomofo.
   * </pre>
   *
   * <code>.taigi.engine.CommitScript script = 7;</code>
   * @return The enum numeric value on the wire for script.
   */
  int getScriptValue();
  /**
   * <pre>
   * R5 — engine-owned commit resolution: the engine resolves the document
   * text from `roman`, `hanji` and the request's `AppConfig`
   * (`composing::commit_text`), answers `ComposingResponse.commit`, and —
   * with the user-data stores open — records the pick's usage itself (the
   * platform sends no `RecordUsage` for it). `UNSPECIFIED` (or a script
   * newer than the engine) is IGNORED. On the TPS layout the romanization
   * written renders as Bopomofo.
   * </pre>
   *
   * <code>.taigi.engine.CommitScript script = 7;</code>
   * @return The script.
   */
  com.siansiansu.taigikeyboard.engine.proto.CommitScript getScript();

  /**
   * <pre>
   * The pick's `CandidateMessage.roman`, as the candidate carried it (POJ-
   * rendered / recased / syllable-separated — the display romanization, never the
   * canonical TL).
   * </pre>
   *
   * <code>string roman = 8;</code>
   * @return The roman.
   */
  java.lang.String getRoman();
  /**
   * <pre>
   * The pick's `CandidateMessage.roman`, as the candidate carried it (POJ-
   * rendered / recased / syllable-separated — the display romanization, never the
   * canonical TL).
   * </pre>
   *
   * <code>string roman = 8;</code>
   * @return The bytes for roman.
   */
  com.google.protobuf.ByteString
      getRomanBytes();
}
