// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf enum {@code taigi.engine.CommitOutcome}
 */
@com.google.protobuf.Generated
public enum CommitOutcome
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>COMMIT_OUTCOME_UNSPECIFIED = 0;</code>
   */
  COMMIT_OUTCOME_UNSPECIFIED(0),
  /**
   * <pre>
   * mid-commit: the composition continues
   * </pre>
   *
   * <code>COMMIT_OUTCOME_NAILED = 1;</code>
   */
  COMMIT_OUTCOME_NAILED(1),
  /**
   * <pre>
   * the buffer was consumed; the engine is Idle
   * </pre>
   *
   * <code>COMMIT_OUTCOME_FINALIZED = 2;</code>
   */
  COMMIT_OUTCOME_FINALIZED(2),
  /**
   * <pre>
   * nothing changed (stale generation, rejected pick)
   * </pre>
   *
   * <code>COMMIT_OUTCOME_IGNORED = 3;</code>
   */
  COMMIT_OUTCOME_IGNORED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>COMMIT_OUTCOME_UNSPECIFIED = 0;</code>
   */
  public static final int COMMIT_OUTCOME_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * mid-commit: the composition continues
   * </pre>
   *
   * <code>COMMIT_OUTCOME_NAILED = 1;</code>
   */
  public static final int COMMIT_OUTCOME_NAILED_VALUE = 1;
  /**
   * <pre>
   * the buffer was consumed; the engine is Idle
   * </pre>
   *
   * <code>COMMIT_OUTCOME_FINALIZED = 2;</code>
   */
  public static final int COMMIT_OUTCOME_FINALIZED_VALUE = 2;
  /**
   * <pre>
   * nothing changed (stale generation, rejected pick)
   * </pre>
   *
   * <code>COMMIT_OUTCOME_IGNORED = 3;</code>
   */
  public static final int COMMIT_OUTCOME_IGNORED_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CommitOutcome valueOf(int value) {
    return forNumber(value);
  }

  public static CommitOutcome forNumber(int value) {
    switch (value) {
      case 0: return COMMIT_OUTCOME_UNSPECIFIED;
      case 1: return COMMIT_OUTCOME_NAILED;
      case 2: return COMMIT_OUTCOME_FINALIZED;
      case 3: return COMMIT_OUTCOME_IGNORED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CommitOutcome>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CommitOutcome> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommitOutcome>() {
          @java.lang.Override
          public CommitOutcome findValueByNumber(int number) {
            return CommitOutcome.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier
      internalGetVerifier() {
    return CommitOutcomeVerifier.INSTANCE;
  }

  private static final class CommitOutcomeVerifier implements
       com.google.protobuf.Internal.EnumVerifier {
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new CommitOutcomeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return CommitOutcome.forNumber(number) != null;
          }
        };

  private final int value;

  private CommitOutcome(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:taigi.engine.CommitOutcome)
}
