// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Which rendering of the picked candidate the document gets (R5).
 * </pre>
 *
 * Protobuf enum {@code taigi.engine.CommitScript}
 */
@com.google.protobuf.Generated
public enum CommitScript
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * no script: the commit is ignored
   * </pre>
   *
   * <code>COMMIT_SCRIPT_UNSPECIFIED = 0;</code>
   */
  COMMIT_SCRIPT_UNSPECIFIED(0),
  /**
   * <pre>
   * what the output settings lead with (Enter / a tap)
   * </pre>
   *
   * <code>COMMIT_SCRIPT_LEAD = 1;</code>
   */
  COMMIT_SCRIPT_LEAD(1),
  /**
   * <pre>
   * the other script of the lead (desktop Space)
   * </pre>
   *
   * <code>COMMIT_SCRIPT_OTHER = 2;</code>
   */
  COMMIT_SCRIPT_OTHER(2),
  /**
   * <pre>
   * a §42 split Hanji cell
   * </pre>
   *
   * <code>COMMIT_SCRIPT_HANJI = 3;</code>
   */
  COMMIT_SCRIPT_HANJI(3),
  /**
   * <pre>
   * a §42 split romanization cell
   * </pre>
   *
   * <code>COMMIT_SCRIPT_ROMAN = 4;</code>
   */
  COMMIT_SCRIPT_ROMAN(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * no script: the commit is ignored
   * </pre>
   *
   * <code>COMMIT_SCRIPT_UNSPECIFIED = 0;</code>
   */
  public static final int COMMIT_SCRIPT_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * what the output settings lead with (Enter / a tap)
   * </pre>
   *
   * <code>COMMIT_SCRIPT_LEAD = 1;</code>
   */
  public static final int COMMIT_SCRIPT_LEAD_VALUE = 1;
  /**
   * <pre>
   * the other script of the lead (desktop Space)
   * </pre>
   *
   * <code>COMMIT_SCRIPT_OTHER = 2;</code>
   */
  public static final int COMMIT_SCRIPT_OTHER_VALUE = 2;
  /**
   * <pre>
   * a §42 split Hanji cell
   * </pre>
   *
   * <code>COMMIT_SCRIPT_HANJI = 3;</code>
   */
  public static final int COMMIT_SCRIPT_HANJI_VALUE = 3;
  /**
   * <pre>
   * a §42 split romanization cell
   * </pre>
   *
   * <code>COMMIT_SCRIPT_ROMAN = 4;</code>
   */
  public static final int COMMIT_SCRIPT_ROMAN_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CommitScript valueOf(int value) {
    return forNumber(value);
  }

  public static CommitScript forNumber(int value) {
    switch (value) {
      case 0: return COMMIT_SCRIPT_UNSPECIFIED;
      case 1: return COMMIT_SCRIPT_LEAD;
      case 2: return COMMIT_SCRIPT_OTHER;
      case 3: return COMMIT_SCRIPT_HANJI;
      case 4: return COMMIT_SCRIPT_ROMAN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CommitScript>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CommitScript> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommitScript>() {
          @java.lang.Override
          public CommitScript findValueByNumber(int number) {
            return CommitScript.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier
      internalGetVerifier() {
    return CommitScriptVerifier.INSTANCE;
  }

  private static final class CommitScriptVerifier implements
       com.google.protobuf.Internal.EnumVerifier {
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new CommitScriptVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return CommitScript.forNumber(number) != null;
          }
        };

  private final int value;

  private CommitScript(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:taigi.engine.CommitScript)
}
