// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * What a `CommitContinuous` did (R5) — replaces the platforms' effect scans.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.CommitResolution}
 */
@com.google.protobuf.Generated
public  final class CommitResolution extends
    com.google.protobuf.GeneratedMessageLite<
        CommitResolution, CommitResolution.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.CommitResolution)
    CommitResolutionOrBuilder {
  private CommitResolution() {
    documentText_ = "";
  }
  public static final int OUTCOME_FIELD_NUMBER = 1;
  private int outcome_;
  /**
   * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
   * @return The enum numeric value on the wire for outcome.
   */
  @java.lang.Override
  public int getOutcomeValue() {
    return outcome_;
  }
  /**
   * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
   * @return The outcome.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.CommitOutcome getOutcome() {
    com.siansiansu.taigikeyboard.engine.proto.CommitOutcome result = com.siansiansu.taigikeyboard.engine.proto.CommitOutcome.forNumber(outcome_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.CommitOutcome.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
   * @param value The enum numeric value on the wire for outcome to set.
   */
  private void setOutcomeValue(int value) {
      outcome_ = value;
  }
  /**
   * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
   * @param value The outcome to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setOutcome(com.siansiansu.taigikeyboard.engine.proto.CommitOutcome value) {
    outcome_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
   */
  private void clearOutcome() {

    outcome_ = 0;
  }

  public static final int DOCUMENT_TEXT_FIELD_NUMBER = 2;
  private java.lang.String documentText_;
  /**
   * <pre>
   * The text this pick wrote into the composition — the segment, not the
   * whole finalized composition. Empty when IGNORED.
   * </pre>
   *
   * <code>string document_text = 2;</code>
   * @return The documentText.
   */
  @java.lang.Override
  public java.lang.String getDocumentText() {
    return documentText_;
  }
  /**
   * <pre>
   * The text this pick wrote into the composition — the segment, not the
   * whole finalized composition. Empty when IGNORED.
   * </pre>
   *
   * <code>string document_text = 2;</code>
   * @return The bytes for documentText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDocumentTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(documentText_);
  }
  /**
   * <pre>
   * The text this pick wrote into the composition — the segment, not the
   * whole finalized composition. Empty when IGNORED.
   * </pre>
   *
   * <code>string document_text = 2;</code>
   * @param value The documentText to set.
   */
  private void setDocumentText(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    documentText_ = value;
  }
  /**
   * <pre>
   * The text this pick wrote into the composition — the segment, not the
   * whole finalized composition. Empty when IGNORED.
   * </pre>
   *
   * <code>string document_text = 2;</code>
   */
  private void clearDocumentText() {

    documentText_ = getDefaultInstance().getDocumentText();
  }
  /**
   * <pre>
   * The text this pick wrote into the composition — the segment, not the
   * whole finalized composition. Empty when IGNORED.
   * </pre>
   *
   * <code>string document_text = 2;</code>
   * @param value The bytes for documentText to set.
   */
  private void setDocumentTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    documentText_ = value.toStringUtf8();

  }

  public static final int WROTE_ROMANIZATION_FIELD_NUMBER = 3;
  private boolean wroteRomanization_;
  /**
   * <pre>
   * `document_text` carries romanization (behavioral-invariants §23).
   * </pre>
   *
   * <code>bool wrote_romanization = 3;</code>
   * @return The wroteRomanization.
   */
  @java.lang.Override
  public boolean getWroteRomanization() {
    return wroteRomanization_;
  }
  /**
   * <pre>
   * `document_text` carries romanization (behavioral-invariants §23).
   * </pre>
   *
   * <code>bool wrote_romanization = 3;</code>
   * @param value The wroteRomanization to set.
   */
  private void setWroteRomanization(boolean value) {

    wroteRomanization_ = value;
  }
  /**
   * <pre>
   * `document_text` carries romanization (behavioral-invariants §23).
   * </pre>
   *
   * <code>bool wrote_romanization = 3;</code>
   */
  private void clearWroteRomanization() {

    wroteRomanization_ = false;
  }

  public static final int EARNS_AUTO_SPACE_FIELD_NUMBER = 4;
  private boolean earnsAutoSpace_;
  /**
   * <pre>
   * FINALIZED &amp;&amp; wrote_romanization &amp;&amp; `document_text` does not end in `-`.
   * The platform still ANDs its live Auto-Space setting.
   * </pre>
   *
   * <code>bool earns_auto_space = 4;</code>
   * @return The earnsAutoSpace.
   */
  @java.lang.Override
  public boolean getEarnsAutoSpace() {
    return earnsAutoSpace_;
  }
  /**
   * <pre>
   * FINALIZED &amp;&amp; wrote_romanization &amp;&amp; `document_text` does not end in `-`.
   * The platform still ANDs its live Auto-Space setting.
   * </pre>
   *
   * <code>bool earns_auto_space = 4;</code>
   * @param value The earnsAutoSpace to set.
   */
  private void setEarnsAutoSpace(boolean value) {

    earnsAutoSpace_ = value;
  }
  /**
   * <pre>
   * FINALIZED &amp;&amp; wrote_romanization &amp;&amp; `document_text` does not end in `-`.
   * The platform still ANDs its live Auto-Space setting.
   * </pre>
   *
   * <code>bool earns_auto_space = 4;</code>
   */
  private void clearEarnsAutoSpace() {

    earnsAutoSpace_ = false;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.CommitResolution prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * What a `CommitContinuous` did (R5) — replaces the platforms' effect scans.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.CommitResolution}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.CommitResolution, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.CommitResolution)
      com.siansiansu.taigikeyboard.engine.proto.CommitResolutionOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.CommitResolution.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
     * @return The enum numeric value on the wire for outcome.
     */
    @java.lang.Override
    public int getOutcomeValue() {
      return instance.getOutcomeValue();
    }
    /**
     * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
     * @param value The outcome to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setOutcomeValue(int value) {
      copyOnWrite();
      instance.setOutcomeValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
     * @return The outcome.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.CommitOutcome getOutcome() {
      return instance.getOutcome();
    }
    /**
     * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
     * @param value The enum numeric value on the wire for outcome to set.
     * @return This builder for chaining.
     */
    public Builder setOutcome(com.siansiansu.taigikeyboard.engine.proto.CommitOutcome value) {
      copyOnWrite();
      instance.setOutcome(value);
      return this;
    }
    /**
     * <code>.taigi.engine.CommitOutcome outcome = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutcome() {
      copyOnWrite();
      instance.clearOutcome();
      return this;
    }

    /**
     * <pre>
     * The text this pick wrote into the composition — the segment, not the
     * whole finalized composition. Empty when IGNORED.
     * </pre>
     *
     * <code>string document_text = 2;</code>
     * @return The documentText.
     */
    @java.lang.Override
    public java.lang.String getDocumentText() {
      return instance.getDocumentText();
    }
    /**
     * <pre>
     * The text this pick wrote into the composition — the segment, not the
     * whole finalized composition. Empty when IGNORED.
     * </pre>
     *
     * <code>string document_text = 2;</code>
     * @return The bytes for documentText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDocumentTextBytes() {
      return instance.getDocumentTextBytes();
    }
    /**
     * <pre>
     * The text this pick wrote into the composition — the segment, not the
     * whole finalized composition. Empty when IGNORED.
     * </pre>
     *
     * <code>string document_text = 2;</code>
     * @param value The documentText to set.
     * @return This builder for chaining.
     */
    public Builder setDocumentText(
        java.lang.String value) {
      copyOnWrite();
      instance.setDocumentText(value);
      return this;
    }
    /**
     * <pre>
     * The text this pick wrote into the composition — the segment, not the
     * whole finalized composition. Empty when IGNORED.
     * </pre>
     *
     * <code>string document_text = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDocumentText() {
      copyOnWrite();
      instance.clearDocumentText();
      return this;
    }
    /**
     * <pre>
     * The text this pick wrote into the composition — the segment, not the
     * whole finalized composition. Empty when IGNORED.
     * </pre>
     *
     * <code>string document_text = 2;</code>
     * @param value The bytes for documentText to set.
     * @return This builder for chaining.
     */
    public Builder setDocumentTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDocumentTextBytes(value);
      return this;
    }

    /**
     * <pre>
     * `document_text` carries romanization (behavioral-invariants §23).
     * </pre>
     *
     * <code>bool wrote_romanization = 3;</code>
     * @return The wroteRomanization.
     */
    @java.lang.Override
    public boolean getWroteRomanization() {
      return instance.getWroteRomanization();
    }
    /**
     * <pre>
     * `document_text` carries romanization (behavioral-invariants §23).
     * </pre>
     *
     * <code>bool wrote_romanization = 3;</code>
     * @param value The wroteRomanization to set.
     * @return This builder for chaining.
     */
    public Builder setWroteRomanization(boolean value) {
      copyOnWrite();
      instance.setWroteRomanization(value);
      return this;
    }
    /**
     * <pre>
     * `document_text` carries romanization (behavioral-invariants §23).
     * </pre>
     *
     * <code>bool wrote_romanization = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWroteRomanization() {
      copyOnWrite();
      instance.clearWroteRomanization();
      return this;
    }

    /**
     * <pre>
     * FINALIZED &amp;&amp; wrote_romanization &amp;&amp; `document_text` does not end in `-`.
     * The platform still ANDs its live Auto-Space setting.
     * </pre>
     *
     * <code>bool earns_auto_space = 4;</code>
     * @return The earnsAutoSpace.
     */
    @java.lang.Override
    public boolean getEarnsAutoSpace() {
      return instance.getEarnsAutoSpace();
    }
    /**
     * <pre>
     * FINALIZED &amp;&amp; wrote_romanization &amp;&amp; `document_text` does not end in `-`.
     * The platform still ANDs its live Auto-Space setting.
     * </pre>
     *
     * <code>bool earns_auto_space = 4;</code>
     * @param value The earnsAutoSpace to set.
     * @return This builder for chaining.
     */
    public Builder setEarnsAutoSpace(boolean value) {
      copyOnWrite();
      instance.setEarnsAutoSpace(value);
      return this;
    }
    /**
     * <pre>
     * FINALIZED &amp;&amp; wrote_romanization &amp;&amp; `document_text` does not end in `-`.
     * The platform still ANDs its live Auto-Space setting.
     * </pre>
     *
     * <code>bool earns_auto_space = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEarnsAutoSpace() {
      copyOnWrite();
      instance.clearEarnsAutoSpace();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.CommitResolution)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.CommitResolution();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "outcome_",
            "documentText_",
            "wroteRomanization_",
            "earnsAutoSpace_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "\u0003\u0007\u0004\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.CommitResolution> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.CommitResolution.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.CommitResolution>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.CommitResolution)
  private static final com.siansiansu.taigikeyboard.engine.proto.CommitResolution DEFAULT_INSTANCE;
  static {
    CommitResolution defaultInstance = new CommitResolution();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CommitResolution.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.CommitResolution getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CommitResolution> PARSER;

  public static com.google.protobuf.Parser<CommitResolution> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
