// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * `ExternalLookupDigitForm` — the digit-tone spelling of a TL reading that
 * the MOE dictionary and ChhoeTaigi search by: lowercased, split on `-`
 * only, per syllable the nasal marks as `nn`, POJ `o͘` as `oo`, the tone as
 * a trailing ASCII digit with tones 1 and 4 omitted, NFC (`tāi-tsì` →
 * `tai7-tsi3`). Answers `StringResult`; the URL itself is the platform's.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.ExternalLookupDigitForm}
 */
@com.google.protobuf.Generated
public  final class ExternalLookupDigitForm extends
    com.google.protobuf.GeneratedMessageLite<
        ExternalLookupDigitForm, ExternalLookupDigitForm.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.ExternalLookupDigitForm)
    ExternalLookupDigitFormOrBuilder {
  private ExternalLookupDigitForm() {
    reading_ = "";
  }
  public static final int READING_FIELD_NUMBER = 1;
  private java.lang.String reading_;
  /**
   * <code>string reading = 1;</code>
   * @return The reading.
   */
  @java.lang.Override
  public java.lang.String getReading() {
    return reading_;
  }
  /**
   * <code>string reading = 1;</code>
   * @return The bytes for reading.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReadingBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reading_);
  }
  /**
   * <code>string reading = 1;</code>
   * @param value The reading to set.
   */
  private void setReading(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    reading_ = value;
  }
  /**
   * <code>string reading = 1;</code>
   */
  private void clearReading() {

    reading_ = getDefaultInstance().getReading();
  }
  /**
   * <code>string reading = 1;</code>
   * @param value The bytes for reading to set.
   */
  private void setReadingBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reading_ = value.toStringUtf8();

  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * `ExternalLookupDigitForm` — the digit-tone spelling of a TL reading that
   * the MOE dictionary and ChhoeTaigi search by: lowercased, split on `-`
   * only, per syllable the nasal marks as `nn`, POJ `o͘` as `oo`, the tone as
   * a trailing ASCII digit with tones 1 and 4 omitted, NFC (`tāi-tsì` →
   * `tai7-tsi3`). Answers `StringResult`; the URL itself is the platform's.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.ExternalLookupDigitForm}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.ExternalLookupDigitForm)
      com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitFormOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string reading = 1;</code>
     * @return The reading.
     */
    @java.lang.Override
    public java.lang.String getReading() {
      return instance.getReading();
    }
    /**
     * <code>string reading = 1;</code>
     * @return The bytes for reading.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReadingBytes() {
      return instance.getReadingBytes();
    }
    /**
     * <code>string reading = 1;</code>
     * @param value The reading to set.
     * @return This builder for chaining.
     */
    public Builder setReading(
        java.lang.String value) {
      copyOnWrite();
      instance.setReading(value);
      return this;
    }
    /**
     * <code>string reading = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReading() {
      copyOnWrite();
      instance.clearReading();
      return this;
    }
    /**
     * <code>string reading = 1;</code>
     * @param value The bytes for reading to set.
     * @return This builder for chaining.
     */
    public Builder setReadingBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReadingBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.ExternalLookupDigitForm)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "reading_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.ExternalLookupDigitForm)
  private static final com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm DEFAULT_INSTANCE;
  static {
    ExternalLookupDigitForm defaultInstance = new ExternalLookupDigitForm();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ExternalLookupDigitForm.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ExternalLookupDigitForm getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ExternalLookupDigitForm> PARSER;

  public static com.google.protobuf.Parser<ExternalLookupDigitForm> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
