// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: phonetics.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface ExternalLookupDigitFormOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.ExternalLookupDigitForm)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string reading = 1;</code>
   * @return The reading.
   */
  java.lang.String getReading();
  /**
   * <code>string reading = 1;</code>
   * @return The bytes for reading.
   */
  com.google.protobuf.ByteString
      getReadingBytes();
}
