// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * v3.5.8 Phase 6 — Pure read: returns the candidate list for the current
 * `Phase::Continuous { raw }` (the whole buffer). The engine builds the
 * `(consumed_span, key)` pairs with `composing::shadow::build_continuous_keys`
 * — one shadow → lattice path for every mode (the hyphen shadow makes
 * `tâi-uân` produce the same `tl:&lt;toneless&gt;` keys as `taiuan`; TPS keys
 * come from the same lattice) — and hands them to
 * `lexicon::fetch_candidates_for_keys_with_barriers`. Emits no effects.
 *
 * The user's own rows — learned counts, custom-dictionary matches, learned
 * phrases — never ride this message: the engine reads them from its
 * user-data stores (`UserDataRequest.open`; user-data-engine-roadmap P9).
 *
 * `now_ms` is the platform's epoch-ms wall clock at fetch time
 * (iOS `Date().timeIntervalSince1970 * 1000`, Android
 * `System.currentTimeMillis()`), the clock the recency ranking reads. The
 * engine guards against `now_ms &lt;= 0`, `last_used_ms &lt;= 0`, and
 * `now_ms &lt; last_used_ms` (clock skew) by falling through to
 * `user_weight = 0.0` for every candidate — see
 * `engine/ranking/src/score.rs::decayed_user_weight_delta`.
 *
 * `toggles` are the user's dictionary switches — the same message Tab3
 * browse (`DictionaryFiltersRequest`) and `PredictNext` carry. The engine
 * resolves them into the source filter itself with the encoder behind
 * `DictionaryFilters`, so keyboard candidates honour the same 12 source
 * toggles + kautian subcollection toggles as browse and no platform
 * computes a bitmask. Absent `toggles` keeps every source on — a default for
 * test fixtures, like fields 6 and 8: the engine ships inside each app, so
 * no platform build without the field reaches it, and every platform in this
 * repository sends them. Toggles with every dictionary off offer no
 * dictionary candidates (§57).
 *
 * §34 / S22 — `literal_roman_candidate_disabled` gates the always-on
 * preedit-literal roman candidate (the `derived_display` WYSIWYG row that
 * `handle_fetch_at_pos` prepends at index 0 in TL/POJ so Hanji-romanization mixing commits
 * the romanization in one tap). It does NOT suppress roman-only / OOV-synth
 * candidates that `assemble_candidates` produces naturally — only the §34
 * forced prepend.
 *
 * SENTINEL (inverted, so the un-wired default is the legacy behaviour):
 * proto3 default `false` means "show" (= pre-toggle always-on
 * behaviour), so older / un-wired builds and proto-decoded fixtures keep the
 * candidate. The platform sends `true` only when the user turns the
 * Show Typed Text First setting OFF. Platform settings stay positive and ship ON on
 * all four platforms (`isLiteralRomanCandidateEnabled` iOS / macOS,
 * `literalRomanCandidateEnabled` Android, `is_literal_roman_candidate_enabled`
 * Windows); the platform sets `disabled = !enabled` — mobile in
 * `ComposingManager`, desktop in the engine bridge.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.FetchAtPos}
 */
@com.google.protobuf.Generated
public  final class FetchAtPos extends
    com.google.protobuf.GeneratedMessageLite<
        FetchAtPos, FetchAtPos.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.FetchAtPos)
    FetchAtPosOrBuilder {
  private FetchAtPos() {
  }
  private int bitField0_;
  public static final int NOW_MS_FIELD_NUMBER = 3;
  private long nowMs_;
  /**
   * <code>int64 now_ms = 3;</code>
   * @return The nowMs.
   */
  @java.lang.Override
  public long getNowMs() {
    return nowMs_;
  }
  /**
   * <code>int64 now_ms = 3;</code>
   * @param value The nowMs to set.
   */
  private void setNowMs(long value) {

    nowMs_ = value;
  }
  /**
   * <code>int64 now_ms = 3;</code>
   */
  private void clearNowMs() {

    nowMs_ = 0L;
  }

  public static final int LITERAL_ROMAN_CANDIDATE_DISABLED_FIELD_NUMBER = 6;
  private boolean literalRomanCandidateDisabled_;
  /**
   * <code>bool literal_roman_candidate_disabled = 6;</code>
   * @return The literalRomanCandidateDisabled.
   */
  @java.lang.Override
  public boolean getLiteralRomanCandidateDisabled() {
    return literalRomanCandidateDisabled_;
  }
  /**
   * <code>bool literal_roman_candidate_disabled = 6;</code>
   * @param value The literalRomanCandidateDisabled to set.
   */
  private void setLiteralRomanCandidateDisabled(boolean value) {

    literalRomanCandidateDisabled_ = value;
  }
  /**
   * <code>bool literal_roman_candidate_disabled = 6;</code>
   */
  private void clearLiteralRomanCandidateDisabled() {

    literalRomanCandidateDisabled_ = false;
  }

  public static final int CUSTOM_DICTIONARY_DISABLED_FIELD_NUMBER = 8;
  private boolean customDictionaryDisabled_;
  /**
   * <pre>
   * The user's "use my custom dictionary" setting, OFF: the engine reads no
   * custom-dictionary rows for this fetch. Negative like field 6, so an
   * un-wired build keeps the dictionary on.
   * </pre>
   *
   * <code>bool custom_dictionary_disabled = 8;</code>
   * @return The customDictionaryDisabled.
   */
  @java.lang.Override
  public boolean getCustomDictionaryDisabled() {
    return customDictionaryDisabled_;
  }
  /**
   * <pre>
   * The user's "use my custom dictionary" setting, OFF: the engine reads no
   * custom-dictionary rows for this fetch. Negative like field 6, so an
   * un-wired build keeps the dictionary on.
   * </pre>
   *
   * <code>bool custom_dictionary_disabled = 8;</code>
   * @param value The customDictionaryDisabled to set.
   */
  private void setCustomDictionaryDisabled(boolean value) {

    customDictionaryDisabled_ = value;
  }
  /**
   * <pre>
   * The user's "use my custom dictionary" setting, OFF: the engine reads no
   * custom-dictionary rows for this fetch. Negative like field 6, so an
   * un-wired build keeps the dictionary on.
   * </pre>
   *
   * <code>bool custom_dictionary_disabled = 8;</code>
   */
  private void clearCustomDictionaryDisabled() {

    customDictionaryDisabled_ = false;
  }

  public static final int TOGGLES_FIELD_NUMBER = 9;
  private com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles toggles_;
  /**
   * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
   */
  @java.lang.Override
  public boolean hasToggles() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles getToggles() {
    return toggles_ == null ? com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.getDefaultInstance() : toggles_;
  }
  /**
   * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
   */
  private void setToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
    java.util.Objects.requireNonNull(value);
    toggles_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
    java.util.Objects.requireNonNull(value);
    if (toggles_ != null &&
        toggles_ != com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.getDefaultInstance()) {
      toggles_ =
        com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.newBuilder(toggles_).mergeFrom(value).buildPartial();
    } else {
      toggles_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
   */
  private void clearToggles() {
    toggles_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.FetchAtPos prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * v3.5.8 Phase 6 — Pure read: returns the candidate list for the current
   * `Phase::Continuous { raw }` (the whole buffer). The engine builds the
   * `(consumed_span, key)` pairs with `composing::shadow::build_continuous_keys`
   * — one shadow → lattice path for every mode (the hyphen shadow makes
   * `tâi-uân` produce the same `tl:&lt;toneless&gt;` keys as `taiuan`; TPS keys
   * come from the same lattice) — and hands them to
   * `lexicon::fetch_candidates_for_keys_with_barriers`. Emits no effects.
   *
   * The user's own rows — learned counts, custom-dictionary matches, learned
   * phrases — never ride this message: the engine reads them from its
   * user-data stores (`UserDataRequest.open`; user-data-engine-roadmap P9).
   *
   * `now_ms` is the platform's epoch-ms wall clock at fetch time
   * (iOS `Date().timeIntervalSince1970 * 1000`, Android
   * `System.currentTimeMillis()`), the clock the recency ranking reads. The
   * engine guards against `now_ms &lt;= 0`, `last_used_ms &lt;= 0`, and
   * `now_ms &lt; last_used_ms` (clock skew) by falling through to
   * `user_weight = 0.0` for every candidate — see
   * `engine/ranking/src/score.rs::decayed_user_weight_delta`.
   *
   * `toggles` are the user's dictionary switches — the same message Tab3
   * browse (`DictionaryFiltersRequest`) and `PredictNext` carry. The engine
   * resolves them into the source filter itself with the encoder behind
   * `DictionaryFilters`, so keyboard candidates honour the same 12 source
   * toggles + kautian subcollection toggles as browse and no platform
   * computes a bitmask. Absent `toggles` keeps every source on — a default for
   * test fixtures, like fields 6 and 8: the engine ships inside each app, so
   * no platform build without the field reaches it, and every platform in this
   * repository sends them. Toggles with every dictionary off offer no
   * dictionary candidates (§57).
   *
   * §34 / S22 — `literal_roman_candidate_disabled` gates the always-on
   * preedit-literal roman candidate (the `derived_display` WYSIWYG row that
   * `handle_fetch_at_pos` prepends at index 0 in TL/POJ so Hanji-romanization mixing commits
   * the romanization in one tap). It does NOT suppress roman-only / OOV-synth
   * candidates that `assemble_candidates` produces naturally — only the §34
   * forced prepend.
   *
   * SENTINEL (inverted, so the un-wired default is the legacy behaviour):
   * proto3 default `false` means "show" (= pre-toggle always-on
   * behaviour), so older / un-wired builds and proto-decoded fixtures keep the
   * candidate. The platform sends `true` only when the user turns the
   * Show Typed Text First setting OFF. Platform settings stay positive and ship ON on
   * all four platforms (`isLiteralRomanCandidateEnabled` iOS / macOS,
   * `literalRomanCandidateEnabled` Android, `is_literal_roman_candidate_enabled`
   * Windows); the platform sets `disabled = !enabled` — mobile in
   * `ComposingManager`, desktop in the engine bridge.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.FetchAtPos}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.FetchAtPos, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.FetchAtPos)
      com.siansiansu.taigikeyboard.engine.proto.FetchAtPosOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.FetchAtPos.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 now_ms = 3;</code>
     * @return The nowMs.
     */
    @java.lang.Override
    public long getNowMs() {
      return instance.getNowMs();
    }
    /**
     * <code>int64 now_ms = 3;</code>
     * @param value The nowMs to set.
     * @return This builder for chaining.
     */
    public Builder setNowMs(long value) {
      copyOnWrite();
      instance.setNowMs(value);
      return this;
    }
    /**
     * <code>int64 now_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNowMs() {
      copyOnWrite();
      instance.clearNowMs();
      return this;
    }

    /**
     * <code>bool literal_roman_candidate_disabled = 6;</code>
     * @return The literalRomanCandidateDisabled.
     */
    @java.lang.Override
    public boolean getLiteralRomanCandidateDisabled() {
      return instance.getLiteralRomanCandidateDisabled();
    }
    /**
     * <code>bool literal_roman_candidate_disabled = 6;</code>
     * @param value The literalRomanCandidateDisabled to set.
     * @return This builder for chaining.
     */
    public Builder setLiteralRomanCandidateDisabled(boolean value) {
      copyOnWrite();
      instance.setLiteralRomanCandidateDisabled(value);
      return this;
    }
    /**
     * <code>bool literal_roman_candidate_disabled = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLiteralRomanCandidateDisabled() {
      copyOnWrite();
      instance.clearLiteralRomanCandidateDisabled();
      return this;
    }

    /**
     * <pre>
     * The user's "use my custom dictionary" setting, OFF: the engine reads no
     * custom-dictionary rows for this fetch. Negative like field 6, so an
     * un-wired build keeps the dictionary on.
     * </pre>
     *
     * <code>bool custom_dictionary_disabled = 8;</code>
     * @return The customDictionaryDisabled.
     */
    @java.lang.Override
    public boolean getCustomDictionaryDisabled() {
      return instance.getCustomDictionaryDisabled();
    }
    /**
     * <pre>
     * The user's "use my custom dictionary" setting, OFF: the engine reads no
     * custom-dictionary rows for this fetch. Negative like field 6, so an
     * un-wired build keeps the dictionary on.
     * </pre>
     *
     * <code>bool custom_dictionary_disabled = 8;</code>
     * @param value The customDictionaryDisabled to set.
     * @return This builder for chaining.
     */
    public Builder setCustomDictionaryDisabled(boolean value) {
      copyOnWrite();
      instance.setCustomDictionaryDisabled(value);
      return this;
    }
    /**
     * <pre>
     * The user's "use my custom dictionary" setting, OFF: the engine reads no
     * custom-dictionary rows for this fetch. Negative like field 6, so an
     * un-wired build keeps the dictionary on.
     * </pre>
     *
     * <code>bool custom_dictionary_disabled = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomDictionaryDisabled() {
      copyOnWrite();
      instance.clearCustomDictionaryDisabled();
      return this;
    }

    /**
     * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
     */
    @java.lang.Override
    public boolean hasToggles() {
      return instance.hasToggles();
    }
    /**
     * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles getToggles() {
      return instance.getToggles();
    }
    /**
     * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
     */
    public Builder setToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
      copyOnWrite();
      instance.setToggles(value);
      return this;
      }
    /**
     * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
     */
    public Builder setToggles(
        com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.Builder builderForValue) {
      copyOnWrite();
      instance.setToggles(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
     */
    public Builder mergeToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
      copyOnWrite();
      instance.mergeToggles(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
     */
    public Builder clearToggles() {  copyOnWrite();
      instance.clearToggles();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.FetchAtPos)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.FetchAtPos();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "nowMs_",
            "literalRomanCandidateDisabled_",
            "customDictionaryDisabled_",
            "toggles_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0001\u0003\t\u0004\u0000\u0000\u0000\u0003\u0002\u0006\u0007" +
              "\b\u0007\t\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.FetchAtPos> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.FetchAtPos.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.FetchAtPos>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.FetchAtPos)
  private static final com.siansiansu.taigikeyboard.engine.proto.FetchAtPos DEFAULT_INSTANCE;
  static {
    FetchAtPos defaultInstance = new FetchAtPos();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FetchAtPos.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.FetchAtPos getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FetchAtPos> PARSER;

  public static com.google.protobuf.Parser<FetchAtPos> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
