// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface FetchAtPosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.FetchAtPos)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 now_ms = 3;</code>
   * @return The nowMs.
   */
  long getNowMs();

  /**
   * <code>bool literal_roman_candidate_disabled = 6;</code>
   * @return The literalRomanCandidateDisabled.
   */
  boolean getLiteralRomanCandidateDisabled();

  /**
   * <pre>
   * The user's "use my custom dictionary" setting, OFF: the engine reads no
   * custom-dictionary rows for this fetch. Negative like field 6, so an
   * un-wired build keeps the dictionary on.
   * </pre>
   *
   * <code>bool custom_dictionary_disabled = 8;</code>
   * @return The customDictionaryDisabled.
   */
  boolean getCustomDictionaryDisabled();

  /**
   * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
   * @return Whether the toggles field is set.
   */
  boolean hasToggles();
  /**
   * <code>.taigi.engine.DictionarySourceToggles toggles = 9;</code>
   * @return The toggles.
   */
  com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles getToggles();

  /**
   * <pre>
   * Under a Hanji conversion the request asks for
   * (`AppConfig.hanji_conversion`, a TPS tail): the list of the word before
   * the caret instead of the whole tail's. The engine resolves the anchor from
   * its own words — the word ending at the caret, else the start of the
   * glyphs the caret is in, `0` at the start of the tail — and lists from
   * there to the end of the tail: longer words first, then the word's
   * homophones, never a phrase of several words. Spans stay in the pending
   * tail's byte coordinates. `false`, or no conversion asked for: the whole
   * tail's list, as without the field.
   * </pre>
   *
   * <code>bool word_before_caret = 10;</code>
   * @return The wordBeforeCaret.
   */
  boolean getWordBeforeCaret();
}
