// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: envelope.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Hanji conversion in the preedit
 * (`docs/architecture/desktop-tps-hanji-conversion-roadmap.md` H1, H2): while
 * the pending buffer is TPS glyphs and the caret is at its end, the engine
 * keeps the walker's best path over the closed readings — closed by a tone
 * mark, or by Space for tones 1 and 4 — and the preedit shows it, followed by
 * the glyphs of the reading still being typed. `Preedit.raw_input` stays the
 * glyphs. TL / POJ buffers are never converted.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.HanjiConversion}
 */
@com.google.protobuf.Generated
public  final class HanjiConversion extends
    com.google.protobuf.GeneratedMessageLite<
        HanjiConversion, HanjiConversion.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.HanjiConversion)
    HanjiConversionOrBuilder {
  private HanjiConversion() {
  }
  private int bitField0_;
  public static final int TOGGLES_FIELD_NUMBER = 1;
  private com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles toggles_;
  /**
   * <pre>
   * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
   * fetch, so the conversion's source filter rides the config. Absent keeps
   * every source on.
   * </pre>
   *
   * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
   */
  @java.lang.Override
  public boolean hasToggles() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
   * fetch, so the conversion's source filter rides the config. Absent keeps
   * every source on.
   * </pre>
   *
   * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles getToggles() {
    return toggles_ == null ? com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.getDefaultInstance() : toggles_;
  }
  /**
   * <pre>
   * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
   * fetch, so the conversion's source filter rides the config. Absent keeps
   * every source on.
   * </pre>
   *
   * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
   */
  private void setToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
    java.util.Objects.requireNonNull(value);
    toggles_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
   * fetch, so the conversion's source filter rides the config. Absent keeps
   * every source on.
   * </pre>
   *
   * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
    java.util.Objects.requireNonNull(value);
    if (toggles_ != null &&
        toggles_ != com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.getDefaultInstance()) {
      toggles_ =
        com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.newBuilder(toggles_).mergeFrom(value).buildPartial();
    } else {
      toggles_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
   * fetch, so the conversion's source filter rides the config. Absent keeps
   * every source on.
   * </pre>
   *
   * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
   */
  private void clearToggles() {
    toggles_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.HanjiConversion prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Hanji conversion in the preedit
   * (`docs/architecture/desktop-tps-hanji-conversion-roadmap.md` H1, H2): while
   * the pending buffer is TPS glyphs and the caret is at its end, the engine
   * keeps the walker's best path over the closed readings — closed by a tone
   * mark, or by Space for tones 1 and 4 — and the preedit shows it, followed by
   * the glyphs of the reading still being typed. `Preedit.raw_input` stays the
   * glyphs. TL / POJ buffers are never converted.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.HanjiConversion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.HanjiConversion, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.HanjiConversion)
      com.siansiansu.taigikeyboard.engine.proto.HanjiConversionOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.HanjiConversion.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
     * fetch, so the conversion's source filter rides the config. Absent keeps
     * every source on.
     * </pre>
     *
     * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
     */
    @java.lang.Override
    public boolean hasToggles() {
      return instance.hasToggles();
    }
    /**
     * <pre>
     * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
     * fetch, so the conversion's source filter rides the config. Absent keeps
     * every source on.
     * </pre>
     *
     * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles getToggles() {
      return instance.getToggles();
    }
    /**
     * <pre>
     * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
     * fetch, so the conversion's source filter rides the config. Absent keeps
     * every source on.
     * </pre>
     *
     * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
     */
    public Builder setToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
      copyOnWrite();
      instance.setToggles(value);
      return this;
      }
    /**
     * <pre>
     * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
     * fetch, so the conversion's source filter rides the config. Absent keeps
     * every source on.
     * </pre>
     *
     * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
     */
    public Builder setToggles(
        com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles.Builder builderForValue) {
      copyOnWrite();
      instance.setToggles(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
     * fetch, so the conversion's source filter rides the config. Absent keeps
     * every source on.
     * </pre>
     *
     * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
     */
    public Builder mergeToggles(com.siansiansu.taigikeyboard.engine.proto.DictionarySourceToggles value) {
      copyOnWrite();
      instance.mergeToggles(value);
      return this;
    }
    /**
     * <pre>
     * The user's dictionary switches, as `FetchAtPos.toggles`: a key carries no
     * fetch, so the conversion's source filter rides the config. Absent keeps
     * every source on.
     * </pre>
     *
     * <code>.taigi.engine.DictionarySourceToggles toggles = 1;</code>
     */
    public Builder clearToggles() {  copyOnWrite();
      instance.clearToggles();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.HanjiConversion)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.HanjiConversion();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "toggles_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.HanjiConversion> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.HanjiConversion.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.HanjiConversion>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.HanjiConversion)
  private static final com.siansiansu.taigikeyboard.engine.proto.HanjiConversion DEFAULT_INSTANCE;
  static {
    HanjiConversion defaultInstance = new HanjiConversion();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HanjiConversion.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.HanjiConversion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HanjiConversion> PARSER;

  public static com.google.protobuf.Parser<HanjiConversion> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
