// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface IsHanjiResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.IsHanjiResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool is_hanji = 1;</code>
   * @return The isHanji.
   */
  boolean getIsHanji();
}
