// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface LearningRecordsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.LearningRecords)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  java.util.List<com.siansiansu.taigikeyboard.engine.proto.LearningRecord>
      getRecordsList();
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecords(int index);
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  int getRecordsCount();

  /**
   * <pre>
   * every row of the kind
   * </pre>
   *
   * <code>uint32 total = 2;</code>
   * @return The total.
   */
  int getTotal();

  /**
   * <pre>
   * the rows `filter` matches, for paging
   * </pre>
   *
   * <code>uint32 matching_total = 3;</code>
   * @return The matchingTotal.
   */
  int getMatchingTotal();

  /**
   * <pre>
   * The offset these records start at: the request's, pulled back to the
   * last page that exists when the matches shrank under it.
   * </pre>
   *
   * <code>uint32 offset = 4;</code>
   * @return The offset.
   */
  int getOffset();
}
