// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf enum {@code taigi.engine.LearningRecordOrder}
 */
@com.google.protobuf.Generated
public enum LearningRecordOrder
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * Largest count first, then most recent.
   * </pre>
   *
   * <code>LEARNING_RECORD_ORDER_MOST_USED = 0;</code>
   */
  LEARNING_RECORD_ORDER_MOST_USED(0),
  /**
   * <pre>
   * Most recently used first, then largest count.
   * </pre>
   *
   * <code>LEARNING_RECORD_ORDER_MOST_RECENT = 1;</code>
   */
  LEARNING_RECORD_ORDER_MOST_RECENT(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Largest count first, then most recent.
   * </pre>
   *
   * <code>LEARNING_RECORD_ORDER_MOST_USED = 0;</code>
   */
  public static final int LEARNING_RECORD_ORDER_MOST_USED_VALUE = 0;
  /**
   * <pre>
   * Most recently used first, then largest count.
   * </pre>
   *
   * <code>LEARNING_RECORD_ORDER_MOST_RECENT = 1;</code>
   */
  public static final int LEARNING_RECORD_ORDER_MOST_RECENT_VALUE = 1;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LearningRecordOrder valueOf(int value) {
    return forNumber(value);
  }

  public static LearningRecordOrder forNumber(int value) {
    switch (value) {
      case 0: return LEARNING_RECORD_ORDER_MOST_USED;
      case 1: return LEARNING_RECORD_ORDER_MOST_RECENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LearningRecordOrder>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LearningRecordOrder> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LearningRecordOrder>() {
          @java.lang.Override
          public LearningRecordOrder findValueByNumber(int number) {
            return LearningRecordOrder.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier
      internalGetVerifier() {
    return LearningRecordOrderVerifier.INSTANCE;
  }

  private static final class LearningRecordOrderVerifier implements
       com.google.protobuf.Internal.EnumVerifier {
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new LearningRecordOrderVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return LearningRecordOrder.forNumber(number) != null;
          }
        };

  private final int value;

  private LearningRecordOrder(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:taigi.engine.LearningRecordOrder)
}
