// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composing.proto
// Protobuf Java Version: 4.36.0

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface LearnedEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.LearnedEntry)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string hanji = 1;</code>
   * @return The hanji.
   */
  java.lang.String getHanji();
  /**
   * <code>string hanji = 1;</code>
   * @return The bytes for hanji.
   */
  com.google.protobuf.ByteString
      getHanjiBytes();

  /**
   * <code>string canonical_tl = 2;</code>
   * @return The canonicalTl.
   */
  java.lang.String getCanonicalTl();
  /**
   * <code>string canonical_tl = 2;</code>
   * @return The bytes for canonicalTl.
   */
  com.google.protobuf.ByteString
      getCanonicalTlBytes();

  /**
   * <pre>
   * How many times the phrase was composed or picked; informational for
   * the engine today (ranking reads `user_frequency` via `frequency_entries`).
   * </pre>
   *
   * <code>uint32 learn_count = 3;</code>
   * @return The learnCount.
   */
  int getLearnCount();
}
