// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface LearningRecordAddedToCustomDictionaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.LearningRecordAddedToCustomDictionary)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
   * @return The enum numeric value on the wire for refusal.
   */
  int getRefusalValue();
  /**
   * <code>.taigi.engine.CustomDictionaryRefusal refusal = 1;</code>
   * @return The refusal.
   */
  com.siansiansu.taigikeyboard.engine.proto.CustomDictionaryRefusal getRefusal();

  /**
   * <pre>
   * The refusal in English, for an alert's diagnostic line; empty when added.
   * </pre>
   *
   * <code>string detail = 2;</code>
   * @return The detail.
   */
  java.lang.String getDetail();
  /**
   * <pre>
   * The refusal in English, for an alert's diagnostic line; empty when added.
   * </pre>
   *
   * <code>string detail = 2;</code>
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString
      getDetailBytes();
}
