// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Counted and read in one read transaction.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.LearningRecords}
 */
@com.google.protobuf.Generated
public  final class LearningRecords extends
    com.google.protobuf.GeneratedMessageLite<
        LearningRecords, LearningRecords.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.LearningRecords)
    LearningRecordsOrBuilder {
  private LearningRecords() {
    records_ = emptyProtobufList();
  }
  public static final int RECORDS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.siansiansu.taigikeyboard.engine.proto.LearningRecord> records_;
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.siansiansu.taigikeyboard.engine.proto.LearningRecord> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  public java.util.List<? extends com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrBuilder>
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  @java.lang.Override
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  public com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }
  private void ensureRecordsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.siansiansu.taigikeyboard.engine.proto.LearningRecord> tmp = records_;
    if (!tmp.isModifiable()) {
      records_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  private void setRecords(
      int index, com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
    java.util.Objects.requireNonNull(value);
    ensureRecordsIsMutable();
    records_.set(index, value);
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  private void addRecords(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
    java.util.Objects.requireNonNull(value);
    ensureRecordsIsMutable();
    records_.add(value);
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  private void addRecords(
      int index, com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
    java.util.Objects.requireNonNull(value);
    ensureRecordsIsMutable();
    records_.add(index, value);
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  private void addAllRecords(
      java.lang.Iterable<? extends com.siansiansu.taigikeyboard.engine.proto.LearningRecord> values) {
    ensureRecordsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, records_);
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  private void clearRecords() {
    records_ = emptyProtobufList();
  }
  /**
   * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
   */
  private void removeRecords(int index) {
    ensureRecordsIsMutable();
    records_.remove(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private int total_;
  /**
   * <pre>
   * every row of the kind
   * </pre>
   *
   * <code>uint32 total = 2;</code>
   * @return The total.
   */
  @java.lang.Override
  public int getTotal() {
    return total_;
  }
  /**
   * <pre>
   * every row of the kind
   * </pre>
   *
   * <code>uint32 total = 2;</code>
   * @param value The total to set.
   */
  private void setTotal(int value) {

    total_ = value;
  }
  /**
   * <pre>
   * every row of the kind
   * </pre>
   *
   * <code>uint32 total = 2;</code>
   */
  private void clearTotal() {

    total_ = 0;
  }

  public static final int MATCHING_TOTAL_FIELD_NUMBER = 3;
  private int matchingTotal_;
  /**
   * <pre>
   * the rows `filter` matches, for paging
   * </pre>
   *
   * <code>uint32 matching_total = 3;</code>
   * @return The matchingTotal.
   */
  @java.lang.Override
  public int getMatchingTotal() {
    return matchingTotal_;
  }
  /**
   * <pre>
   * the rows `filter` matches, for paging
   * </pre>
   *
   * <code>uint32 matching_total = 3;</code>
   * @param value The matchingTotal to set.
   */
  private void setMatchingTotal(int value) {

    matchingTotal_ = value;
  }
  /**
   * <pre>
   * the rows `filter` matches, for paging
   * </pre>
   *
   * <code>uint32 matching_total = 3;</code>
   */
  private void clearMatchingTotal() {

    matchingTotal_ = 0;
  }

  public static final int OFFSET_FIELD_NUMBER = 4;
  private int offset_;
  /**
   * <pre>
   * The offset these records start at: the request's, pulled back to the
   * last page that exists when the matches shrank under it.
   * </pre>
   *
   * <code>uint32 offset = 4;</code>
   * @return The offset.
   */
  @java.lang.Override
  public int getOffset() {
    return offset_;
  }
  /**
   * <pre>
   * The offset these records start at: the request's, pulled back to the
   * last page that exists when the matches shrank under it.
   * </pre>
   *
   * <code>uint32 offset = 4;</code>
   * @param value The offset to set.
   */
  private void setOffset(int value) {

    offset_ = value;
  }
  /**
   * <pre>
   * The offset these records start at: the request's, pulled back to the
   * last page that exists when the matches shrank under it.
   * </pre>
   *
   * <code>uint32 offset = 4;</code>
   */
  private void clearOffset() {

    offset_ = 0;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.LearningRecords prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Counted and read in one read transaction.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.LearningRecords}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.LearningRecords, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.LearningRecords)
      com.siansiansu.taigikeyboard.engine.proto.LearningRecordsOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.LearningRecords.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.siansiansu.taigikeyboard.engine.proto.LearningRecord> getRecordsList() {
      return java.util.Collections.unmodifiableList(
          instance.getRecordsList());
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    @java.lang.Override
    public int getRecordsCount() {
      return instance.getRecordsCount();
    }/**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecords(int index) {
      return instance.getRecords(index);
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder setRecords(
        int index, com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
      copyOnWrite();
      instance.setRecords(index, value);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder setRecords(
        int index, com.siansiansu.taigikeyboard.engine.proto.LearningRecord.Builder builderForValue) {
      copyOnWrite();
      instance.setRecords(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder addRecords(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
      copyOnWrite();
      instance.addRecords(value);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder addRecords(
        int index, com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
      copyOnWrite();
      instance.addRecords(index, value);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder addRecords(
        com.siansiansu.taigikeyboard.engine.proto.LearningRecord.Builder builderForValue) {
      copyOnWrite();
      instance.addRecords(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder addRecords(
        int index, com.siansiansu.taigikeyboard.engine.proto.LearningRecord.Builder builderForValue) {
      copyOnWrite();
      instance.addRecords(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends com.siansiansu.taigikeyboard.engine.proto.LearningRecord> values) {
      copyOnWrite();
      instance.addAllRecords(values);
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder clearRecords() {
      copyOnWrite();
      instance.clearRecords();
      return this;
    }
    /**
     * <code>repeated .taigi.engine.LearningRecord records = 1;</code>
     */
    public Builder removeRecords(int index) {
      copyOnWrite();
      instance.removeRecords(index);
      return this;
    }

    /**
     * <pre>
     * every row of the kind
     * </pre>
     *
     * <code>uint32 total = 2;</code>
     * @return The total.
     */
    @java.lang.Override
    public int getTotal() {
      return instance.getTotal();
    }
    /**
     * <pre>
     * every row of the kind
     * </pre>
     *
     * <code>uint32 total = 2;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(int value) {
      copyOnWrite();
      instance.setTotal(value);
      return this;
    }
    /**
     * <pre>
     * every row of the kind
     * </pre>
     *
     * <code>uint32 total = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      copyOnWrite();
      instance.clearTotal();
      return this;
    }

    /**
     * <pre>
     * the rows `filter` matches, for paging
     * </pre>
     *
     * <code>uint32 matching_total = 3;</code>
     * @return The matchingTotal.
     */
    @java.lang.Override
    public int getMatchingTotal() {
      return instance.getMatchingTotal();
    }
    /**
     * <pre>
     * the rows `filter` matches, for paging
     * </pre>
     *
     * <code>uint32 matching_total = 3;</code>
     * @param value The matchingTotal to set.
     * @return This builder for chaining.
     */
    public Builder setMatchingTotal(int value) {
      copyOnWrite();
      instance.setMatchingTotal(value);
      return this;
    }
    /**
     * <pre>
     * the rows `filter` matches, for paging
     * </pre>
     *
     * <code>uint32 matching_total = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatchingTotal() {
      copyOnWrite();
      instance.clearMatchingTotal();
      return this;
    }

    /**
     * <pre>
     * The offset these records start at: the request's, pulled back to the
     * last page that exists when the matches shrank under it.
     * </pre>
     *
     * <code>uint32 offset = 4;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return instance.getOffset();
    }
    /**
     * <pre>
     * The offset these records start at: the request's, pulled back to the
     * last page that exists when the matches shrank under it.
     * </pre>
     *
     * <code>uint32 offset = 4;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(int value) {
      copyOnWrite();
      instance.setOffset(value);
      return this;
    }
    /**
     * <pre>
     * The offset these records start at: the request's, pulled back to the
     * last page that exists when the matches shrank under it.
     * </pre>
     *
     * <code>uint32 offset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      copyOnWrite();
      instance.clearOffset();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.LearningRecords)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.LearningRecords();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "records_",
            com.siansiansu.taigikeyboard.engine.proto.LearningRecord.class,
            "total_",
            "matchingTotal_",
            "offset_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0001\u0000\u0001\u001b\u0002\u000b" +
              "\u0003\u000b\u0004\u000b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.LearningRecords> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.LearningRecords.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.LearningRecords>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.LearningRecords)
  private static final com.siansiansu.taigikeyboard.engine.proto.LearningRecords DEFAULT_INSTANCE;
  static {
    LearningRecords defaultInstance = new LearningRecords();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LearningRecords.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LearningRecords getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LearningRecords> PARSER;

  public static com.google.protobuf.Parser<LearningRecords> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
