// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: lexicon.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf type {@code taigi.engine.LexiconRequest}
 */
@com.google.protobuf.Generated
public  final class LexiconRequest extends
    com.google.protobuf.GeneratedMessageLite<
        LexiconRequest, LexiconRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.LexiconRequest)
    LexiconRequestOrBuilder {
  private LexiconRequest() {
  }
  private int methodCase_ = 0;
  private java.lang.Object method_;
  public enum MethodCase
      implements com.google.protobuf.AbstractMessageLite.InternalOneOfEnum {
    INSTALL(11),
    SEARCH_WITH_SOURCES(13),
    SEARCH_BY_HANJI(14),
    IS_HANJI(17),
    DICTIONARY_FILTERS(18),
    METHOD_NOT_SET(0);
    private final int value;
    private MethodCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MethodCase valueOf(int value) {
      return forNumber(value);
    }

    public static MethodCase forNumber(int value) {
      switch (value) {
        case 11: return INSTALL;
        case 13: return SEARCH_WITH_SOURCES;
        case 14: return SEARCH_BY_HANJI;
        case 17: return IS_HANJI;
        case 18: return DICTIONARY_FILTERS;
        case 0: return METHOD_NOT_SET;
        default: return null;
      }
    }
    @java.lang.Override public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public MethodCase
  getMethodCase() {
    return MethodCase.forNumber(
        methodCase_);
  }

  private void clearMethod() {
    methodCase_ = 0;
    method_ = null;
  }

  public static final int INSTALL_FIELD_NUMBER = 11;
  /**
   * <pre>
   * lexicon read-path
   * </pre>
   *
   * <code>.taigi.engine.InstallRequest install = 11;</code>
   */
  @java.lang.Override
  public boolean hasInstall() {
    return methodCase_ == 11;
  }
  /**
   * <pre>
   * lexicon read-path
   * </pre>
   *
   * <code>.taigi.engine.InstallRequest install = 11;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.InstallRequest getInstall() {
    if (methodCase_ == 11) {
       return (com.siansiansu.taigikeyboard.engine.proto.InstallRequest) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.InstallRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * lexicon read-path
   * </pre>
   *
   * <code>.taigi.engine.InstallRequest install = 11;</code>
   */
  private void setInstall(com.siansiansu.taigikeyboard.engine.proto.InstallRequest value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 11;
  }
  /**
   * <pre>
   * lexicon read-path
   * </pre>
   *
   * <code>.taigi.engine.InstallRequest install = 11;</code>
   */
  private void mergeInstall(com.siansiansu.taigikeyboard.engine.proto.InstallRequest value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 11 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.InstallRequest.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.InstallRequest.newBuilder((com.siansiansu.taigikeyboard.engine.proto.InstallRequest) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 11;
  }
  /**
   * <pre>
   * lexicon read-path
   * </pre>
   *
   * <code>.taigi.engine.InstallRequest install = 11;</code>
   */
  private void clearInstall() {
    if (methodCase_ == 11) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int SEARCH_WITH_SOURCES_FIELD_NUMBER = 13;
  /**
   * <pre>
   * Tab3 multi-source
   * </pre>
   *
   * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
   */
  @java.lang.Override
  public boolean hasSearchWithSources() {
    return methodCase_ == 13;
  }
  /**
   * <pre>
   * Tab3 multi-source
   * </pre>
   *
   * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest getSearchWithSources() {
    if (methodCase_ == 13) {
       return (com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * Tab3 multi-source
   * </pre>
   *
   * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
   */
  private void setSearchWithSources(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 13;
  }
  /**
   * <pre>
   * Tab3 multi-source
   * </pre>
   *
   * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
   */
  private void mergeSearchWithSources(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 13 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 13;
  }
  /**
   * <pre>
   * Tab3 multi-source
   * </pre>
   *
   * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
   */
  private void clearSearchWithSources() {
    if (methodCase_ == 13) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int SEARCH_BY_HANJI_FIELD_NUMBER = 14;
  /**
   * <pre>
   * Tab3 Hanji prefix
   * </pre>
   *
   * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
   */
  @java.lang.Override
  public boolean hasSearchByHanji() {
    return methodCase_ == 14;
  }
  /**
   * <pre>
   * Tab3 Hanji prefix
   * </pre>
   *
   * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest getSearchByHanji() {
    if (methodCase_ == 14) {
       return (com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * Tab3 Hanji prefix
   * </pre>
   *
   * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
   */
  private void setSearchByHanji(com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 14;
  }
  /**
   * <pre>
   * Tab3 Hanji prefix
   * </pre>
   *
   * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
   */
  private void mergeSearchByHanji(com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 14 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 14;
  }
  /**
   * <pre>
   * Tab3 Hanji prefix
   * </pre>
   *
   * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
   */
  private void clearSearchByHanji() {
    if (methodCase_ == 14) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int IS_HANJI_FIELD_NUMBER = 17;
  /**
   * <pre>
   * v3.5.7 Tab3 short-circuit
   * </pre>
   *
   * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
   */
  @java.lang.Override
  public boolean hasIsHanji() {
    return methodCase_ == 17;
  }
  /**
   * <pre>
   * v3.5.7 Tab3 short-circuit
   * </pre>
   *
   * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest getIsHanji() {
    if (methodCase_ == 17) {
       return (com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * v3.5.7 Tab3 short-circuit
   * </pre>
   *
   * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
   */
  private void setIsHanji(com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 17;
  }
  /**
   * <pre>
   * v3.5.7 Tab3 short-circuit
   * </pre>
   *
   * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
   */
  private void mergeIsHanji(com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 17 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest.newBuilder((com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 17;
  }
  /**
   * <pre>
   * v3.5.7 Tab3 short-circuit
   * </pre>
   *
   * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
   */
  private void clearIsHanji() {
    if (methodCase_ == 17) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int DICTIONARY_FILTERS_FIELD_NUMBER = 18;
  /**
   * <pre>
   * v3.5.8 toggles → bitmasks + enabled codes
   * </pre>
   *
   * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
   */
  @java.lang.Override
  public boolean hasDictionaryFilters() {
    return methodCase_ == 18;
  }
  /**
   * <pre>
   * v3.5.8 toggles → bitmasks + enabled codes
   * </pre>
   *
   * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest getDictionaryFilters() {
    if (methodCase_ == 18) {
       return (com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * v3.5.8 toggles → bitmasks + enabled codes
   * </pre>
   *
   * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
   */
  private void setDictionaryFilters(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 18;
  }
  /**
   * <pre>
   * v3.5.8 toggles → bitmasks + enabled codes
   * </pre>
   *
   * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
   */
  private void mergeDictionaryFilters(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 18 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest.newBuilder((com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 18;
  }
  /**
   * <pre>
   * v3.5.8 toggles → bitmasks + enabled codes
   * </pre>
   *
   * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
   */
  private void clearDictionaryFilters() {
    if (methodCase_ == 18) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.LexiconRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code taigi.engine.LexiconRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.LexiconRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.LexiconRequest)
      com.siansiansu.taigikeyboard.engine.proto.LexiconRequestOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.LexiconRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public MethodCase
        getMethodCase() {
      return instance.getMethodCase();
    }

    public Builder clearMethod() {
      copyOnWrite();
      instance.clearMethod();
      return this;
    }


    /**
     * <pre>
     * lexicon read-path
     * </pre>
     *
     * <code>.taigi.engine.InstallRequest install = 11;</code>
     */
    @java.lang.Override
    public boolean hasInstall() {
      return instance.hasInstall();
    }
    /**
     * <pre>
     * lexicon read-path
     * </pre>
     *
     * <code>.taigi.engine.InstallRequest install = 11;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.InstallRequest getInstall() {
      return instance.getInstall();
    }
    /**
     * <pre>
     * lexicon read-path
     * </pre>
     *
     * <code>.taigi.engine.InstallRequest install = 11;</code>
     */
    public Builder setInstall(com.siansiansu.taigikeyboard.engine.proto.InstallRequest value) {
      copyOnWrite();
      instance.setInstall(value);
      return this;
    }
    /**
     * <pre>
     * lexicon read-path
     * </pre>
     *
     * <code>.taigi.engine.InstallRequest install = 11;</code>
     */
    public Builder setInstall(
        com.siansiansu.taigikeyboard.engine.proto.InstallRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setInstall(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * lexicon read-path
     * </pre>
     *
     * <code>.taigi.engine.InstallRequest install = 11;</code>
     */
    public Builder mergeInstall(com.siansiansu.taigikeyboard.engine.proto.InstallRequest value) {
      copyOnWrite();
      instance.mergeInstall(value);
      return this;
    }
    /**
     * <pre>
     * lexicon read-path
     * </pre>
     *
     * <code>.taigi.engine.InstallRequest install = 11;</code>
     */
    public Builder clearInstall() {
      copyOnWrite();
      instance.clearInstall();
      return this;
    }

    /**
     * <pre>
     * Tab3 multi-source
     * </pre>
     *
     * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
     */
    @java.lang.Override
    public boolean hasSearchWithSources() {
      return instance.hasSearchWithSources();
    }
    /**
     * <pre>
     * Tab3 multi-source
     * </pre>
     *
     * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest getSearchWithSources() {
      return instance.getSearchWithSources();
    }
    /**
     * <pre>
     * Tab3 multi-source
     * </pre>
     *
     * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
     */
    public Builder setSearchWithSources(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest value) {
      copyOnWrite();
      instance.setSearchWithSources(value);
      return this;
    }
    /**
     * <pre>
     * Tab3 multi-source
     * </pre>
     *
     * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
     */
    public Builder setSearchWithSources(
        com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchWithSources(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Tab3 multi-source
     * </pre>
     *
     * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
     */
    public Builder mergeSearchWithSources(com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest value) {
      copyOnWrite();
      instance.mergeSearchWithSources(value);
      return this;
    }
    /**
     * <pre>
     * Tab3 multi-source
     * </pre>
     *
     * <code>.taigi.engine.SearchWithSourcesRequest search_with_sources = 13;</code>
     */
    public Builder clearSearchWithSources() {
      copyOnWrite();
      instance.clearSearchWithSources();
      return this;
    }

    /**
     * <pre>
     * Tab3 Hanji prefix
     * </pre>
     *
     * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
     */
    @java.lang.Override
    public boolean hasSearchByHanji() {
      return instance.hasSearchByHanji();
    }
    /**
     * <pre>
     * Tab3 Hanji prefix
     * </pre>
     *
     * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest getSearchByHanji() {
      return instance.getSearchByHanji();
    }
    /**
     * <pre>
     * Tab3 Hanji prefix
     * </pre>
     *
     * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
     */
    public Builder setSearchByHanji(com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest value) {
      copyOnWrite();
      instance.setSearchByHanji(value);
      return this;
    }
    /**
     * <pre>
     * Tab3 Hanji prefix
     * </pre>
     *
     * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
     */
    public Builder setSearchByHanji(
        com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchByHanji(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Tab3 Hanji prefix
     * </pre>
     *
     * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
     */
    public Builder mergeSearchByHanji(com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest value) {
      copyOnWrite();
      instance.mergeSearchByHanji(value);
      return this;
    }
    /**
     * <pre>
     * Tab3 Hanji prefix
     * </pre>
     *
     * <code>.taigi.engine.SearchByHanjiRequest search_by_hanji = 14;</code>
     */
    public Builder clearSearchByHanji() {
      copyOnWrite();
      instance.clearSearchByHanji();
      return this;
    }

    /**
     * <pre>
     * v3.5.7 Tab3 short-circuit
     * </pre>
     *
     * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
     */
    @java.lang.Override
    public boolean hasIsHanji() {
      return instance.hasIsHanji();
    }
    /**
     * <pre>
     * v3.5.7 Tab3 short-circuit
     * </pre>
     *
     * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest getIsHanji() {
      return instance.getIsHanji();
    }
    /**
     * <pre>
     * v3.5.7 Tab3 short-circuit
     * </pre>
     *
     * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
     */
    public Builder setIsHanji(com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest value) {
      copyOnWrite();
      instance.setIsHanji(value);
      return this;
    }
    /**
     * <pre>
     * v3.5.7 Tab3 short-circuit
     * </pre>
     *
     * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
     */
    public Builder setIsHanji(
        com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setIsHanji(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * v3.5.7 Tab3 short-circuit
     * </pre>
     *
     * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
     */
    public Builder mergeIsHanji(com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest value) {
      copyOnWrite();
      instance.mergeIsHanji(value);
      return this;
    }
    /**
     * <pre>
     * v3.5.7 Tab3 short-circuit
     * </pre>
     *
     * <code>.taigi.engine.IsHanjiRequest is_hanji = 17;</code>
     */
    public Builder clearIsHanji() {
      copyOnWrite();
      instance.clearIsHanji();
      return this;
    }

    /**
     * <pre>
     * v3.5.8 toggles → bitmasks + enabled codes
     * </pre>
     *
     * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
     */
    @java.lang.Override
    public boolean hasDictionaryFilters() {
      return instance.hasDictionaryFilters();
    }
    /**
     * <pre>
     * v3.5.8 toggles → bitmasks + enabled codes
     * </pre>
     *
     * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest getDictionaryFilters() {
      return instance.getDictionaryFilters();
    }
    /**
     * <pre>
     * v3.5.8 toggles → bitmasks + enabled codes
     * </pre>
     *
     * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
     */
    public Builder setDictionaryFilters(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest value) {
      copyOnWrite();
      instance.setDictionaryFilters(value);
      return this;
    }
    /**
     * <pre>
     * v3.5.8 toggles → bitmasks + enabled codes
     * </pre>
     *
     * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
     */
    public Builder setDictionaryFilters(
        com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setDictionaryFilters(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * v3.5.8 toggles → bitmasks + enabled codes
     * </pre>
     *
     * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
     */
    public Builder mergeDictionaryFilters(com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest value) {
      copyOnWrite();
      instance.mergeDictionaryFilters(value);
      return this;
    }
    /**
     * <pre>
     * v3.5.8 toggles → bitmasks + enabled codes
     * </pre>
     *
     * <code>.taigi.engine.DictionaryFiltersRequest dictionary_filters = 18;</code>
     */
    public Builder clearDictionaryFilters() {
      copyOnWrite();
      instance.clearDictionaryFilters();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.LexiconRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.LexiconRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "method_",
            "methodCase_",
            com.siansiansu.taigikeyboard.engine.proto.InstallRequest.class,
            com.siansiansu.taigikeyboard.engine.proto.SearchWithSourcesRequest.class,
            com.siansiansu.taigikeyboard.engine.proto.SearchByHanjiRequest.class,
            com.siansiansu.taigikeyboard.engine.proto.IsHanjiRequest.class,
            com.siansiansu.taigikeyboard.engine.proto.DictionaryFiltersRequest.class,
          };
          java.lang.String info =
              "\u0000\u0005\u0001\u0000\u000b\u0012\u0005\u0000\u0000\u0000\u000b<\u0000\r<\u0000" +
              "\u000e<\u0000\u0011<\u0000\u0012<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.LexiconRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.LexiconRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.LexiconRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.LexiconRequest)
  private static final com.siansiansu.taigikeyboard.engine.proto.LexiconRequest DEFAULT_INSTANCE;
  static {
    LexiconRequest defaultInstance = new LexiconRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      LexiconRequest.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.LexiconRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LexiconRequest> PARSER;

  public static com.google.protobuf.Parser<LexiconRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
