// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * A page of one kind. `filter` matches the text or the TL (either side of
 * an association) as a substring; empty lists everything. `limit` 0 is
 * refused: a store holds up to 50 000 rows.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.ListLearningRecords}
 */
@com.google.protobuf.Generated
public  final class ListLearningRecords extends
    com.google.protobuf.GeneratedMessageLite<
        ListLearningRecords, ListLearningRecords.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.ListLearningRecords)
    ListLearningRecordsOrBuilder {
  private ListLearningRecords() {
    filter_ = "";
  }
  public static final int KIND_FIELD_NUMBER = 1;
  private int kind_;
  /**
   * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
   * @return The kind.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind getKind() {
    com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind result = com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind.forNumber(kind_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
   * @param value The enum numeric value on the wire for kind to set.
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
   * @param value The kind to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setKind(com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind value) {
    kind_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
   */
  private void clearKind() {

    kind_ = 0;
  }

  public static final int FILTER_FIELD_NUMBER = 2;
  private java.lang.String filter_;
  /**
   * <code>string filter = 2;</code>
   * @return The filter.
   */
  @java.lang.Override
  public java.lang.String getFilter() {
    return filter_;
  }
  /**
   * <code>string filter = 2;</code>
   * @return The bytes for filter.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilterBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(filter_);
  }
  /**
   * <code>string filter = 2;</code>
   * @param value The filter to set.
   */
  private void setFilter(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    filter_ = value;
  }
  /**
   * <code>string filter = 2;</code>
   */
  private void clearFilter() {

    filter_ = getDefaultInstance().getFilter();
  }
  /**
   * <code>string filter = 2;</code>
   * @param value The bytes for filter to set.
   */
  private void setFilterBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    filter_ = value.toStringUtf8();

  }

  public static final int LIMIT_FIELD_NUMBER = 3;
  private int limit_;
  /**
   * <code>uint32 limit = 3;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }
  /**
   * <code>uint32 limit = 3;</code>
   * @param value The limit to set.
   */
  private void setLimit(int value) {

    limit_ = value;
  }
  /**
   * <code>uint32 limit = 3;</code>
   */
  private void clearLimit() {

    limit_ = 0;
  }

  public static final int OFFSET_FIELD_NUMBER = 4;
  private int offset_;
  /**
   * <code>uint32 offset = 4;</code>
   * @return The offset.
   */
  @java.lang.Override
  public int getOffset() {
    return offset_;
  }
  /**
   * <code>uint32 offset = 4;</code>
   * @param value The offset to set.
   */
  private void setOffset(int value) {

    offset_ = value;
  }
  /**
   * <code>uint32 offset = 4;</code>
   */
  private void clearOffset() {

    offset_ = 0;
  }

  public static final int ORDER_FIELD_NUMBER = 5;
  private int order_;
  /**
   * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
   * @return The enum numeric value on the wire for order.
   */
  @java.lang.Override
  public int getOrderValue() {
    return order_;
  }
  /**
   * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
   * @return The order.
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder getOrder() {
    com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder result = com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder.forNumber(order_);
    return result == null ? com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder.UNRECOGNIZED : result;
  }
  /**
   * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
   * @param value The enum numeric value on the wire for order to set.
   */
  private void setOrderValue(int value) {
      order_ = value;
  }
  /**
   * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
   * @param value The order to set.
   * @throws IllegalArgumentException if UNRECOGNIZED is provided.
   */
  private void setOrder(com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder value) {
    order_ = value.getNumber();

  }
  /**
   * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
   */
  private void clearOrder() {

    order_ = 0;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A page of one kind. `filter` matches the text or the TL (either side of
   * an association) as a substring; empty lists everything. `limit` 0 is
   * refused: a store holds up to 50 000 rows.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.ListLearningRecords}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.ListLearningRecords)
      com.siansiansu.taigikeyboard.engine.proto.ListLearningRecordsOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
     * @param value The kind to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
     * @return The kind.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind getKind() {
      return instance.getKind();
    }
    /**
     * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    /**
     * <code>string filter = 2;</code>
     * @return The filter.
     */
    @java.lang.Override
    public java.lang.String getFilter() {
      return instance.getFilter();
    }
    /**
     * <code>string filter = 2;</code>
     * @return The bytes for filter.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilterBytes() {
      return instance.getFilterBytes();
    }
    /**
     * <code>string filter = 2;</code>
     * @param value The filter to set.
     * @return This builder for chaining.
     */
    public Builder setFilter(
        java.lang.String value) {
      copyOnWrite();
      instance.setFilter(value);
      return this;
    }
    /**
     * <code>string filter = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilter() {
      copyOnWrite();
      instance.clearFilter();
      return this;
    }
    /**
     * <code>string filter = 2;</code>
     * @param value The bytes for filter to set.
     * @return This builder for chaining.
     */
    public Builder setFilterBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFilterBytes(value);
      return this;
    }

    /**
     * <code>uint32 limit = 3;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return instance.getLimit();
    }
    /**
     * <code>uint32 limit = 3;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {
      copyOnWrite();
      instance.setLimit(value);
      return this;
    }
    /**
     * <code>uint32 limit = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      copyOnWrite();
      instance.clearLimit();
      return this;
    }

    /**
     * <code>uint32 offset = 4;</code>
     * @return The offset.
     */
    @java.lang.Override
    public int getOffset() {
      return instance.getOffset();
    }
    /**
     * <code>uint32 offset = 4;</code>
     * @param value The offset to set.
     * @return This builder for chaining.
     */
    public Builder setOffset(int value) {
      copyOnWrite();
      instance.setOffset(value);
      return this;
    }
    /**
     * <code>uint32 offset = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOffset() {
      copyOnWrite();
      instance.clearOffset();
      return this;
    }

    /**
     * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
     * @return The enum numeric value on the wire for order.
     */
    @java.lang.Override
    public int getOrderValue() {
      return instance.getOrderValue();
    }
    /**
     * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
     * @param value The order to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setOrderValue(int value) {
      copyOnWrite();
      instance.setOrderValue(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
     * @return The order.
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder getOrder() {
      return instance.getOrder();
    }
    /**
     * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
     * @param value The enum numeric value on the wire for order to set.
     * @return This builder for chaining.
     */
    public Builder setOrder(com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder value) {
      copyOnWrite();
      instance.setOrder(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrder() {
      copyOnWrite();
      instance.clearOrder();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.ListLearningRecords)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "kind_",
            "filter_",
            "limit_",
            "offset_",
            "order_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\u0208" +
              "\u0003\u000b\u0004\u000b\u0005\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.ListLearningRecords)
  private static final com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords DEFAULT_INSTANCE;
  static {
    ListLearningRecords defaultInstance = new ListLearningRecords();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListLearningRecords.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListLearningRecords> PARSER;

  public static com.google.protobuf.Parser<ListLearningRecords> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
