// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface ListLearningRecordsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.ListLearningRecords)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.taigi.engine.LearningRecordKind kind = 1;</code>
   * @return The kind.
   */
  com.siansiansu.taigikeyboard.engine.proto.LearningRecordKind getKind();

  /**
   * <code>string filter = 2;</code>
   * @return The filter.
   */
  java.lang.String getFilter();
  /**
   * <code>string filter = 2;</code>
   * @return The bytes for filter.
   */
  com.google.protobuf.ByteString
      getFilterBytes();

  /**
   * <code>uint32 limit = 3;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>uint32 offset = 4;</code>
   * @return The offset.
   */
  int getOffset();

  /**
   * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
   * @return The enum numeric value on the wire for order.
   */
  int getOrderValue();
  /**
   * <code>.taigi.engine.LearningRecordOrder order = 5;</code>
   * @return The order.
   */
  com.siansiansu.taigikeyboard.engine.proto.LearningRecordOrder getOrder();
}
