// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Sets one row's count, clamped to 1..=1 000 000; the row's last-used time
 * is kept (an edit is not a use). `record` is the row as the page listed
 * it: the write applies only while the row with that `id` still holds that
 * text and TL — a row id can be reused after a delete.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.SetLearningRecordCount}
 */
@com.google.protobuf.Generated
public  final class SetLearningRecordCount extends
    com.google.protobuf.GeneratedMessageLite<
        SetLearningRecordCount, SetLearningRecordCount.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.SetLearningRecordCount)
    SetLearningRecordCountOrBuilder {
  private SetLearningRecordCount() {
  }
  private int bitField0_;
  public static final int RECORD_FIELD_NUMBER = 1;
  private com.siansiansu.taigikeyboard.engine.proto.LearningRecord record_;
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  @java.lang.Override
  public boolean hasRecord() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecord() {
    return record_ == null ? com.siansiansu.taigikeyboard.engine.proto.LearningRecord.getDefaultInstance() : record_;
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  private void setRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
    java.util.Objects.requireNonNull(value);
    record_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
    java.util.Objects.requireNonNull(value);
    if (record_ != null &&
        record_ != com.siansiansu.taigikeyboard.engine.proto.LearningRecord.getDefaultInstance()) {
      record_ =
        com.siansiansu.taigikeyboard.engine.proto.LearningRecord.newBuilder(record_).mergeFrom(value).buildPartial();
    } else {
      record_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.taigi.engine.LearningRecord record = 1;</code>
   */
  private void clearRecord() {
    record_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private long count_;
  /**
   * <code>int64 count = 2;</code>
   * @return The count.
   */
  @java.lang.Override
  public long getCount() {
    return count_;
  }
  /**
   * <code>int64 count = 2;</code>
   * @param value The count to set.
   */
  private void setCount(long value) {

    count_ = value;
  }
  /**
   * <code>int64 count = 2;</code>
   */
  private void clearCount() {

    count_ = 0L;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Sets one row's count, clamped to 1..=1 000 000; the row's last-used time
   * is kept (an edit is not a use). `record` is the row as the page listed
   * it: the write applies only while the row with that `id` still holds that
   * text and TL — a row id can be reused after a delete.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.SetLearningRecordCount}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.SetLearningRecordCount)
      com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCountOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    @java.lang.Override
    public boolean hasRecord() {
      return instance.hasRecord();
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.LearningRecord getRecord() {
      return instance.getRecord();
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder setRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
      copyOnWrite();
      instance.setRecord(value);
      return this;
      }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder setRecord(
        com.siansiansu.taigikeyboard.engine.proto.LearningRecord.Builder builderForValue) {
      copyOnWrite();
      instance.setRecord(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder mergeRecord(com.siansiansu.taigikeyboard.engine.proto.LearningRecord value) {
      copyOnWrite();
      instance.mergeRecord(value);
      return this;
    }
    /**
     * <code>.taigi.engine.LearningRecord record = 1;</code>
     */
    public Builder clearRecord() {  copyOnWrite();
      instance.clearRecord();
      return this;
    }

    /**
     * <code>int64 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return instance.getCount();
    }
    /**
     * <code>int64 count = 2;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {
      copyOnWrite();
      instance.setCount(value);
      return this;
    }
    /**
     * <code>int64 count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      copyOnWrite();
      instance.clearCount();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.SetLearningRecordCount)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "record_",
            "count_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\u0002";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.SetLearningRecordCount)
  private static final com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount DEFAULT_INSTANCE;
  static {
    SetLearningRecordCount defaultInstance = new SetLearningRecordCount();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SetLearningRecordCount.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SetLearningRecordCount> PARSER;

  public static com.google.protobuf.Parser<SetLearningRecordCount> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
