// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface SetPredictionsVisibleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.SetPredictionsVisible)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool visible = 1;</code>
   * @return The visible.
   */
  boolean getVisible();
}
