// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: nextword.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Platform → engine visibility sync. Pushes the prediction bar's visibility
 * to state after platform rendering of an async predict() result. No effects,
 * no generation bump; just state.predictions_visible = visible.
 * </pre>
 *
 * Protobuf type {@code taigi.engine.SetPredictionsVisible}
 */
@com.google.protobuf.Generated
public  final class SetPredictionsVisible extends
    com.google.protobuf.GeneratedMessageLite<
        SetPredictionsVisible, SetPredictionsVisible.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.SetPredictionsVisible)
    SetPredictionsVisibleOrBuilder {
  private SetPredictionsVisible() {
  }
  public static final int VISIBLE_FIELD_NUMBER = 1;
  private boolean visible_;
  /**
   * <code>bool visible = 1;</code>
   * @return The visible.
   */
  @java.lang.Override
  public boolean getVisible() {
    return visible_;
  }
  /**
   * <code>bool visible = 1;</code>
   * @param value The visible to set.
   */
  private void setVisible(boolean value) {

    visible_ = value;
  }
  /**
   * <code>bool visible = 1;</code>
   */
  private void clearVisible() {

    visible_ = false;
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Platform → engine visibility sync. Pushes the prediction bar's visibility
   * to state after platform rendering of an async predict() result. No effects,
   * no generation bump; just state.predictions_visible = visible.
   * </pre>
   *
   * Protobuf type {@code taigi.engine.SetPredictionsVisible}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.SetPredictionsVisible)
      com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisibleOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool visible = 1;</code>
     * @return The visible.
     */
    @java.lang.Override
    public boolean getVisible() {
      return instance.getVisible();
    }
    /**
     * <code>bool visible = 1;</code>
     * @param value The visible to set.
     * @return This builder for chaining.
     */
    public Builder setVisible(boolean value) {
      copyOnWrite();
      instance.setVisible(value);
      return this;
    }
    /**
     * <code>bool visible = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVisible() {
      copyOnWrite();
      instance.clearVisible();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.SetPredictionsVisible)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "visible_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.SetPredictionsVisible)
  private static final com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible DEFAULT_INSTANCE;
  static {
    SetPredictionsVisible defaultInstance = new SetPredictionsVisible();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SetPredictionsVisible.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.SetPredictionsVisible getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SetPredictionsVisible> PARSER;

  public static com.google.protobuf.Parser<SetPredictionsVisible> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
