// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: envelope.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * How the rendered romanization separates syllables (Syllable Separator,
 * `behavioral-invariants.md` §49). `UNSPECIFIED` (proto3 default) and any
 * unknown value mean HYPHEN — the dictionary form; normalise through
 * `AppConfig::rendered_syllable_joiner`, never compare the raw i32.
 * </pre>
 *
 * Protobuf enum {@code taigi.engine.SyllableSeparator}
 */
@com.google.protobuf.Generated
public enum SyllableSeparator
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>SYLLABLE_SEPARATOR_UNSPECIFIED = 0;</code>
   */
  SYLLABLE_SEPARATOR_UNSPECIFIED(0),
  /**
   * <code>SYLLABLE_SEPARATOR_HYPHEN = 1;</code>
   */
  SYLLABLE_SEPARATOR_HYPHEN(1),
  /**
   * <code>SYLLABLE_SEPARATOR_NONE = 2;</code>
   */
  SYLLABLE_SEPARATOR_NONE(2),
  /**
   * <code>SYLLABLE_SEPARATOR_SPACE = 3;</code>
   */
  SYLLABLE_SEPARATOR_SPACE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>SYLLABLE_SEPARATOR_UNSPECIFIED = 0;</code>
   */
  public static final int SYLLABLE_SEPARATOR_UNSPECIFIED_VALUE = 0;
  /**
   * <code>SYLLABLE_SEPARATOR_HYPHEN = 1;</code>
   */
  public static final int SYLLABLE_SEPARATOR_HYPHEN_VALUE = 1;
  /**
   * <code>SYLLABLE_SEPARATOR_NONE = 2;</code>
   */
  public static final int SYLLABLE_SEPARATOR_NONE_VALUE = 2;
  /**
   * <code>SYLLABLE_SEPARATOR_SPACE = 3;</code>
   */
  public static final int SYLLABLE_SEPARATOR_SPACE_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      return com.google.protobuf.Internal.throwCannotGetNumberOfUnrecognized();
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SyllableSeparator valueOf(int value) {
    return forNumber(value);
  }

  public static SyllableSeparator forNumber(int value) {
    switch (value) {
      case 0: return SYLLABLE_SEPARATOR_UNSPECIFIED;
      case 1: return SYLLABLE_SEPARATOR_HYPHEN;
      case 2: return SYLLABLE_SEPARATOR_NONE;
      case 3: return SYLLABLE_SEPARATOR_SPACE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SyllableSeparator>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SyllableSeparator> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SyllableSeparator>() {
          @java.lang.Override
          public SyllableSeparator findValueByNumber(int number) {
            return SyllableSeparator.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier
      internalGetVerifier() {
    return SyllableSeparatorVerifier.INSTANCE;
  }

  private static final class SyllableSeparatorVerifier implements
       com.google.protobuf.Internal.EnumVerifier {
          static final com.google.protobuf.Internal.EnumVerifier
              INSTANCE = new SyllableSeparatorVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return SyllableSeparator.forNumber(number) != null;
          }
        };

  private final int value;

  private SyllableSeparator(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:taigi.engine.SyllableSeparator)
}
