// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

@com.google.protobuf.Generated
public interface UserDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:taigi.engine.UserDataRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.taigi.engine.OpenUserData open = 1;</code>
   * @return Whether the open field is set.
   */
  boolean hasOpen();
  /**
   * <code>.taigi.engine.OpenUserData open = 1;</code>
   * @return The open.
   */
  com.siansiansu.taigikeyboard.engine.proto.OpenUserData getOpen();

  /**
   * <code>.taigi.engine.ResetUserData reset = 2;</code>
   * @return Whether the reset field is set.
   */
  boolean hasReset();
  /**
   * <code>.taigi.engine.ResetUserData reset = 2;</code>
   * @return The reset.
   */
  com.siansiansu.taigikeyboard.engine.proto.ResetUserData getReset();

  /**
   * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
   * @return Whether the recordUsage field is set.
   */
  boolean hasRecordUsage();
  /**
   * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
   * @return The recordUsage.
   */
  com.siansiansu.taigikeyboard.engine.proto.RecordUsage getRecordUsage();

  /**
   * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
   * @return Whether the listCustomEntries field is set.
   */
  boolean hasListCustomEntries();
  /**
   * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
   * @return The listCustomEntries.
   */
  com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries getListCustomEntries();

  /**
   * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
   * @return Whether the saveCustomEntry field is set.
   */
  boolean hasSaveCustomEntry();
  /**
   * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
   * @return The saveCustomEntry.
   */
  com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry getSaveCustomEntry();

  /**
   * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
   * @return Whether the deleteCustomEntry field is set.
   */
  boolean hasDeleteCustomEntry();
  /**
   * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
   * @return The deleteCustomEntry.
   */
  com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry getDeleteCustomEntry();

  /**
   * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
   * @return Whether the importCustomCsv field is set.
   */
  boolean hasImportCustomCsv();
  /**
   * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
   * @return The importCustomCsv.
   */
  com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv getImportCustomCsv();

  /**
   * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
   * @return Whether the exportCustomCsv field is set.
   */
  boolean hasExportCustomCsv();
  /**
   * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
   * @return The exportCustomCsv.
   */
  com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv getExportCustomCsv();

  /**
   * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
   * @return Whether the exportBackup field is set.
   */
  boolean hasExportBackup();
  /**
   * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
   * @return The exportBackup.
   */
  com.siansiansu.taigikeyboard.engine.proto.ExportBackup getExportBackup();

  /**
   * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
   * @return Whether the importBackup field is set.
   */
  boolean hasImportBackup();
  /**
   * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
   * @return The importBackup.
   */
  com.siansiansu.taigikeyboard.engine.proto.ImportBackup getImportBackup();

  /**
   * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
   * @return Whether the searchCustomEntries field is set.
   */
  boolean hasSearchCustomEntries();
  /**
   * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
   * @return The searchCustomEntries.
   */
  com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries getSearchCustomEntries();

  /**
   * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
   * @return Whether the listLearningRecords field is set.
   */
  boolean hasListLearningRecords();
  /**
   * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
   * @return The listLearningRecords.
   */
  com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords getListLearningRecords();

  /**
   * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
   * @return Whether the setLearningRecordCount field is set.
   */
  boolean hasSetLearningRecordCount();
  /**
   * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
   * @return The setLearningRecordCount.
   */
  com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount getSetLearningRecordCount();

  /**
   * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
   * @return Whether the deleteLearningRecord field is set.
   */
  boolean hasDeleteLearningRecord();
  /**
   * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
   * @return The deleteLearningRecord.
   */
  com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord getDeleteLearningRecord();

  /**
   * <code>.taigi.engine.AddLearningRecordToCustomDictionary add_learning_record_to_custom_dictionary = 15;</code>
   * @return Whether the addLearningRecordToCustomDictionary field is set.
   */
  boolean hasAddLearningRecordToCustomDictionary();
  /**
   * <code>.taigi.engine.AddLearningRecordToCustomDictionary add_learning_record_to_custom_dictionary = 15;</code>
   * @return The addLearningRecordToCustomDictionary.
   */
  com.siansiansu.taigikeyboard.engine.proto.AddLearningRecordToCustomDictionary getAddLearningRecordToCustomDictionary();

  public com.siansiansu.taigikeyboard.engine.proto.UserDataRequest.MethodCase getMethodCase();
}
