// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * Protobuf type {@code taigi.engine.UserDataRequest}
 */
@com.google.protobuf.Generated
public  final class UserDataRequest extends
    com.google.protobuf.GeneratedMessageLite<
        UserDataRequest, UserDataRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.UserDataRequest)
    UserDataRequestOrBuilder {
  private UserDataRequest() {
  }
  private int methodCase_ = 0;
  private java.lang.Object method_;
  public enum MethodCase
      implements com.google.protobuf.AbstractMessageLite.InternalOneOfEnum {
    OPEN(1),
    RESET(2),
    RECORD_USAGE(3),
    LIST_CUSTOM_ENTRIES(4),
    SAVE_CUSTOM_ENTRY(5),
    DELETE_CUSTOM_ENTRY(6),
    IMPORT_CUSTOM_CSV(7),
    EXPORT_CUSTOM_CSV(8),
    EXPORT_BACKUP(9),
    IMPORT_BACKUP(10),
    SEARCH_CUSTOM_ENTRIES(11),
    LIST_LEARNING_RECORDS(12),
    SET_LEARNING_RECORD_COUNT(13),
    DELETE_LEARNING_RECORD(14),
    MOVE_LEARNING_RECORD_TO_CUSTOM_DICTIONARY(15),
    METHOD_NOT_SET(0);
    private final int value;
    private MethodCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MethodCase valueOf(int value) {
      return forNumber(value);
    }

    public static MethodCase forNumber(int value) {
      switch (value) {
        case 1: return OPEN;
        case 2: return RESET;
        case 3: return RECORD_USAGE;
        case 4: return LIST_CUSTOM_ENTRIES;
        case 5: return SAVE_CUSTOM_ENTRY;
        case 6: return DELETE_CUSTOM_ENTRY;
        case 7: return IMPORT_CUSTOM_CSV;
        case 8: return EXPORT_CUSTOM_CSV;
        case 9: return EXPORT_BACKUP;
        case 10: return IMPORT_BACKUP;
        case 11: return SEARCH_CUSTOM_ENTRIES;
        case 12: return LIST_LEARNING_RECORDS;
        case 13: return SET_LEARNING_RECORD_COUNT;
        case 14: return DELETE_LEARNING_RECORD;
        case 15: return MOVE_LEARNING_RECORD_TO_CUSTOM_DICTIONARY;
        case 0: return METHOD_NOT_SET;
        default: return null;
      }
    }
    @java.lang.Override public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public MethodCase
  getMethodCase() {
    return MethodCase.forNumber(
        methodCase_);
  }

  private void clearMethod() {
    methodCase_ = 0;
    method_ = null;
  }

  public static final int OPEN_FIELD_NUMBER = 1;
  /**
   * <code>.taigi.engine.OpenUserData open = 1;</code>
   */
  @java.lang.Override
  public boolean hasOpen() {
    return methodCase_ == 1;
  }
  /**
   * <code>.taigi.engine.OpenUserData open = 1;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.OpenUserData getOpen() {
    if (methodCase_ == 1) {
       return (com.siansiansu.taigikeyboard.engine.proto.OpenUserData) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.OpenUserData.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.OpenUserData open = 1;</code>
   */
  private void setOpen(com.siansiansu.taigikeyboard.engine.proto.OpenUserData value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 1;
  }
  /**
   * <code>.taigi.engine.OpenUserData open = 1;</code>
   */
  private void mergeOpen(com.siansiansu.taigikeyboard.engine.proto.OpenUserData value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 1 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.OpenUserData.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.OpenUserData.newBuilder((com.siansiansu.taigikeyboard.engine.proto.OpenUserData) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 1;
  }
  /**
   * <code>.taigi.engine.OpenUserData open = 1;</code>
   */
  private void clearOpen() {
    if (methodCase_ == 1) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int RESET_FIELD_NUMBER = 2;
  /**
   * <code>.taigi.engine.ResetUserData reset = 2;</code>
   */
  @java.lang.Override
  public boolean hasReset() {
    return methodCase_ == 2;
  }
  /**
   * <code>.taigi.engine.ResetUserData reset = 2;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ResetUserData getReset() {
    if (methodCase_ == 2) {
       return (com.siansiansu.taigikeyboard.engine.proto.ResetUserData) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ResetUserData.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ResetUserData reset = 2;</code>
   */
  private void setReset(com.siansiansu.taigikeyboard.engine.proto.ResetUserData value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 2;
  }
  /**
   * <code>.taigi.engine.ResetUserData reset = 2;</code>
   */
  private void mergeReset(com.siansiansu.taigikeyboard.engine.proto.ResetUserData value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 2 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ResetUserData.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ResetUserData.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ResetUserData) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 2;
  }
  /**
   * <code>.taigi.engine.ResetUserData reset = 2;</code>
   */
  private void clearReset() {
    if (methodCase_ == 2) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int RECORD_USAGE_FIELD_NUMBER = 3;
  /**
   * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
   */
  @java.lang.Override
  public boolean hasRecordUsage() {
    return methodCase_ == 3;
  }
  /**
   * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.RecordUsage getRecordUsage() {
    if (methodCase_ == 3) {
       return (com.siansiansu.taigikeyboard.engine.proto.RecordUsage) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.RecordUsage.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
   */
  private void setRecordUsage(com.siansiansu.taigikeyboard.engine.proto.RecordUsage value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 3;
  }
  /**
   * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
   */
  private void mergeRecordUsage(com.siansiansu.taigikeyboard.engine.proto.RecordUsage value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 3 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.RecordUsage.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.RecordUsage.newBuilder((com.siansiansu.taigikeyboard.engine.proto.RecordUsage) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 3;
  }
  /**
   * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
   */
  private void clearRecordUsage() {
    if (methodCase_ == 3) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int LIST_CUSTOM_ENTRIES_FIELD_NUMBER = 4;
  /**
   * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
   */
  @java.lang.Override
  public boolean hasListCustomEntries() {
    return methodCase_ == 4;
  }
  /**
   * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries getListCustomEntries() {
    if (methodCase_ == 4) {
       return (com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
   */
  private void setListCustomEntries(com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 4;
  }
  /**
   * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
   */
  private void mergeListCustomEntries(com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 4 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 4;
  }
  /**
   * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
   */
  private void clearListCustomEntries() {
    if (methodCase_ == 4) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int SAVE_CUSTOM_ENTRY_FIELD_NUMBER = 5;
  /**
   * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
   */
  @java.lang.Override
  public boolean hasSaveCustomEntry() {
    return methodCase_ == 5;
  }
  /**
   * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry getSaveCustomEntry() {
    if (methodCase_ == 5) {
       return (com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
   */
  private void setSaveCustomEntry(com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 5;
  }
  /**
   * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
   */
  private void mergeSaveCustomEntry(com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 5 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 5;
  }
  /**
   * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
   */
  private void clearSaveCustomEntry() {
    if (methodCase_ == 5) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int DELETE_CUSTOM_ENTRY_FIELD_NUMBER = 6;
  /**
   * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
   */
  @java.lang.Override
  public boolean hasDeleteCustomEntry() {
    return methodCase_ == 6;
  }
  /**
   * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry getDeleteCustomEntry() {
    if (methodCase_ == 6) {
       return (com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
   */
  private void setDeleteCustomEntry(com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 6;
  }
  /**
   * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
   */
  private void mergeDeleteCustomEntry(com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 6 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry.newBuilder((com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 6;
  }
  /**
   * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
   */
  private void clearDeleteCustomEntry() {
    if (methodCase_ == 6) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int IMPORT_CUSTOM_CSV_FIELD_NUMBER = 7;
  /**
   * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
   */
  @java.lang.Override
  public boolean hasImportCustomCsv() {
    return methodCase_ == 7;
  }
  /**
   * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv getImportCustomCsv() {
    if (methodCase_ == 7) {
       return (com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
   */
  private void setImportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 7;
  }
  /**
   * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
   */
  private void mergeImportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 7 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 7;
  }
  /**
   * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
   */
  private void clearImportCustomCsv() {
    if (methodCase_ == 7) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int EXPORT_CUSTOM_CSV_FIELD_NUMBER = 8;
  /**
   * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
   */
  @java.lang.Override
  public boolean hasExportCustomCsv() {
    return methodCase_ == 8;
  }
  /**
   * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv getExportCustomCsv() {
    if (methodCase_ == 8) {
       return (com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
   */
  private void setExportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 8;
  }
  /**
   * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
   */
  private void mergeExportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 8 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 8;
  }
  /**
   * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
   */
  private void clearExportCustomCsv() {
    if (methodCase_ == 8) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int EXPORT_BACKUP_FIELD_NUMBER = 9;
  /**
   * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
   */
  @java.lang.Override
  public boolean hasExportBackup() {
    return methodCase_ == 9;
  }
  /**
   * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ExportBackup getExportBackup() {
    if (methodCase_ == 9) {
       return (com.siansiansu.taigikeyboard.engine.proto.ExportBackup) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ExportBackup.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
   */
  private void setExportBackup(com.siansiansu.taigikeyboard.engine.proto.ExportBackup value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 9;
  }
  /**
   * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
   */
  private void mergeExportBackup(com.siansiansu.taigikeyboard.engine.proto.ExportBackup value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 9 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ExportBackup.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ExportBackup.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ExportBackup) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 9;
  }
  /**
   * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
   */
  private void clearExportBackup() {
    if (methodCase_ == 9) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int IMPORT_BACKUP_FIELD_NUMBER = 10;
  /**
   * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
   */
  @java.lang.Override
  public boolean hasImportBackup() {
    return methodCase_ == 10;
  }
  /**
   * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ImportBackup getImportBackup() {
    if (methodCase_ == 10) {
       return (com.siansiansu.taigikeyboard.engine.proto.ImportBackup) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ImportBackup.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
   */
  private void setImportBackup(com.siansiansu.taigikeyboard.engine.proto.ImportBackup value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 10;
  }
  /**
   * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
   */
  private void mergeImportBackup(com.siansiansu.taigikeyboard.engine.proto.ImportBackup value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 10 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ImportBackup.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ImportBackup.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ImportBackup) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 10;
  }
  /**
   * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
   */
  private void clearImportBackup() {
    if (methodCase_ == 10) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int SEARCH_CUSTOM_ENTRIES_FIELD_NUMBER = 11;
  /**
   * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
   */
  @java.lang.Override
  public boolean hasSearchCustomEntries() {
    return methodCase_ == 11;
  }
  /**
   * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries getSearchCustomEntries() {
    if (methodCase_ == 11) {
       return (com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
   */
  private void setSearchCustomEntries(com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 11;
  }
  /**
   * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
   */
  private void mergeSearchCustomEntries(com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 11 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 11;
  }
  /**
   * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
   */
  private void clearSearchCustomEntries() {
    if (methodCase_ == 11) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int LIST_LEARNING_RECORDS_FIELD_NUMBER = 12;
  /**
   * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
   */
  @java.lang.Override
  public boolean hasListLearningRecords() {
    return methodCase_ == 12;
  }
  /**
   * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords getListLearningRecords() {
    if (methodCase_ == 12) {
       return (com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
   */
  private void setListLearningRecords(com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 12;
  }
  /**
   * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
   */
  private void mergeListLearningRecords(com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 12 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords.newBuilder((com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 12;
  }
  /**
   * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
   */
  private void clearListLearningRecords() {
    if (methodCase_ == 12) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int SET_LEARNING_RECORD_COUNT_FIELD_NUMBER = 13;
  /**
   * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
   */
  @java.lang.Override
  public boolean hasSetLearningRecordCount() {
    return methodCase_ == 13;
  }
  /**
   * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount getSetLearningRecordCount() {
    if (methodCase_ == 13) {
       return (com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
   */
  private void setSetLearningRecordCount(com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 13;
  }
  /**
   * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
   */
  private void mergeSetLearningRecordCount(com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 13 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount.newBuilder((com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 13;
  }
  /**
   * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
   */
  private void clearSetLearningRecordCount() {
    if (methodCase_ == 13) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int DELETE_LEARNING_RECORD_FIELD_NUMBER = 14;
  /**
   * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
   */
  @java.lang.Override
  public boolean hasDeleteLearningRecord() {
    return methodCase_ == 14;
  }
  /**
   * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord getDeleteLearningRecord() {
    if (methodCase_ == 14) {
       return (com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
   */
  private void setDeleteLearningRecord(com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 14;
  }
  /**
   * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
   */
  private void mergeDeleteLearningRecord(com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 14 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord.newBuilder((com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 14;
  }
  /**
   * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
   */
  private void clearDeleteLearningRecord() {
    if (methodCase_ == 14) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static final int MOVE_LEARNING_RECORD_TO_CUSTOM_DICTIONARY_FIELD_NUMBER = 15;
  /**
   * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
   */
  @java.lang.Override
  public boolean hasMoveLearningRecordToCustomDictionary() {
    return methodCase_ == 15;
  }
  /**
   * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
   */
  @java.lang.Override
  public com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary getMoveLearningRecordToCustomDictionary() {
    if (methodCase_ == 15) {
       return (com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary) method_;
    }
    return com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary.getDefaultInstance();
  }
  /**
   * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
   */
  private void setMoveLearningRecordToCustomDictionary(com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary value) {
    java.util.Objects.requireNonNull(value);
    method_ = value;
    methodCase_ = 15;
  }
  /**
   * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
   */
  private void mergeMoveLearningRecordToCustomDictionary(com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary value) {
    java.util.Objects.requireNonNull(value);
    if (methodCase_ == 15 &&
        method_ != com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary.getDefaultInstance()) {
      method_ = com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary.newBuilder((com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary) method_)
          .mergeFrom(value).buildPartial();
    } else {
      method_ = value;
    }
    methodCase_ = 15;
  }
  /**
   * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
   */
  private void clearMoveLearningRecordToCustomDictionary() {
    if (methodCase_ == 15) {
      methodCase_ = 0;
      method_ = null;
    }
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.UserDataRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code taigi.engine.UserDataRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.UserDataRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.UserDataRequest)
      com.siansiansu.taigikeyboard.engine.proto.UserDataRequestOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.UserDataRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public MethodCase
        getMethodCase() {
      return instance.getMethodCase();
    }

    public Builder clearMethod() {
      copyOnWrite();
      instance.clearMethod();
      return this;
    }


    /**
     * <code>.taigi.engine.OpenUserData open = 1;</code>
     */
    @java.lang.Override
    public boolean hasOpen() {
      return instance.hasOpen();
    }
    /**
     * <code>.taigi.engine.OpenUserData open = 1;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.OpenUserData getOpen() {
      return instance.getOpen();
    }
    /**
     * <code>.taigi.engine.OpenUserData open = 1;</code>
     */
    public Builder setOpen(com.siansiansu.taigikeyboard.engine.proto.OpenUserData value) {
      copyOnWrite();
      instance.setOpen(value);
      return this;
    }
    /**
     * <code>.taigi.engine.OpenUserData open = 1;</code>
     */
    public Builder setOpen(
        com.siansiansu.taigikeyboard.engine.proto.OpenUserData.Builder builderForValue) {
      copyOnWrite();
      instance.setOpen(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.OpenUserData open = 1;</code>
     */
    public Builder mergeOpen(com.siansiansu.taigikeyboard.engine.proto.OpenUserData value) {
      copyOnWrite();
      instance.mergeOpen(value);
      return this;
    }
    /**
     * <code>.taigi.engine.OpenUserData open = 1;</code>
     */
    public Builder clearOpen() {
      copyOnWrite();
      instance.clearOpen();
      return this;
    }

    /**
     * <code>.taigi.engine.ResetUserData reset = 2;</code>
     */
    @java.lang.Override
    public boolean hasReset() {
      return instance.hasReset();
    }
    /**
     * <code>.taigi.engine.ResetUserData reset = 2;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ResetUserData getReset() {
      return instance.getReset();
    }
    /**
     * <code>.taigi.engine.ResetUserData reset = 2;</code>
     */
    public Builder setReset(com.siansiansu.taigikeyboard.engine.proto.ResetUserData value) {
      copyOnWrite();
      instance.setReset(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ResetUserData reset = 2;</code>
     */
    public Builder setReset(
        com.siansiansu.taigikeyboard.engine.proto.ResetUserData.Builder builderForValue) {
      copyOnWrite();
      instance.setReset(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ResetUserData reset = 2;</code>
     */
    public Builder mergeReset(com.siansiansu.taigikeyboard.engine.proto.ResetUserData value) {
      copyOnWrite();
      instance.mergeReset(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ResetUserData reset = 2;</code>
     */
    public Builder clearReset() {
      copyOnWrite();
      instance.clearReset();
      return this;
    }

    /**
     * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
     */
    @java.lang.Override
    public boolean hasRecordUsage() {
      return instance.hasRecordUsage();
    }
    /**
     * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.RecordUsage getRecordUsage() {
      return instance.getRecordUsage();
    }
    /**
     * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
     */
    public Builder setRecordUsage(com.siansiansu.taigikeyboard.engine.proto.RecordUsage value) {
      copyOnWrite();
      instance.setRecordUsage(value);
      return this;
    }
    /**
     * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
     */
    public Builder setRecordUsage(
        com.siansiansu.taigikeyboard.engine.proto.RecordUsage.Builder builderForValue) {
      copyOnWrite();
      instance.setRecordUsage(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
     */
    public Builder mergeRecordUsage(com.siansiansu.taigikeyboard.engine.proto.RecordUsage value) {
      copyOnWrite();
      instance.mergeRecordUsage(value);
      return this;
    }
    /**
     * <code>.taigi.engine.RecordUsage record_usage = 3;</code>
     */
    public Builder clearRecordUsage() {
      copyOnWrite();
      instance.clearRecordUsage();
      return this;
    }

    /**
     * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
     */
    @java.lang.Override
    public boolean hasListCustomEntries() {
      return instance.hasListCustomEntries();
    }
    /**
     * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries getListCustomEntries() {
      return instance.getListCustomEntries();
    }
    /**
     * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
     */
    public Builder setListCustomEntries(com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries value) {
      copyOnWrite();
      instance.setListCustomEntries(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
     */
    public Builder setListCustomEntries(
        com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries.Builder builderForValue) {
      copyOnWrite();
      instance.setListCustomEntries(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
     */
    public Builder mergeListCustomEntries(com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries value) {
      copyOnWrite();
      instance.mergeListCustomEntries(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ListCustomEntries list_custom_entries = 4;</code>
     */
    public Builder clearListCustomEntries() {
      copyOnWrite();
      instance.clearListCustomEntries();
      return this;
    }

    /**
     * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
     */
    @java.lang.Override
    public boolean hasSaveCustomEntry() {
      return instance.hasSaveCustomEntry();
    }
    /**
     * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry getSaveCustomEntry() {
      return instance.getSaveCustomEntry();
    }
    /**
     * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
     */
    public Builder setSaveCustomEntry(com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry value) {
      copyOnWrite();
      instance.setSaveCustomEntry(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
     */
    public Builder setSaveCustomEntry(
        com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry.Builder builderForValue) {
      copyOnWrite();
      instance.setSaveCustomEntry(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
     */
    public Builder mergeSaveCustomEntry(com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry value) {
      copyOnWrite();
      instance.mergeSaveCustomEntry(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SaveCustomEntry save_custom_entry = 5;</code>
     */
    public Builder clearSaveCustomEntry() {
      copyOnWrite();
      instance.clearSaveCustomEntry();
      return this;
    }

    /**
     * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
     */
    @java.lang.Override
    public boolean hasDeleteCustomEntry() {
      return instance.hasDeleteCustomEntry();
    }
    /**
     * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry getDeleteCustomEntry() {
      return instance.getDeleteCustomEntry();
    }
    /**
     * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
     */
    public Builder setDeleteCustomEntry(com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry value) {
      copyOnWrite();
      instance.setDeleteCustomEntry(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
     */
    public Builder setDeleteCustomEntry(
        com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry.Builder builderForValue) {
      copyOnWrite();
      instance.setDeleteCustomEntry(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
     */
    public Builder mergeDeleteCustomEntry(com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry value) {
      copyOnWrite();
      instance.mergeDeleteCustomEntry(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DeleteCustomEntry delete_custom_entry = 6;</code>
     */
    public Builder clearDeleteCustomEntry() {
      copyOnWrite();
      instance.clearDeleteCustomEntry();
      return this;
    }

    /**
     * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
     */
    @java.lang.Override
    public boolean hasImportCustomCsv() {
      return instance.hasImportCustomCsv();
    }
    /**
     * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv getImportCustomCsv() {
      return instance.getImportCustomCsv();
    }
    /**
     * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
     */
    public Builder setImportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv value) {
      copyOnWrite();
      instance.setImportCustomCsv(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
     */
    public Builder setImportCustomCsv(
        com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv.Builder builderForValue) {
      copyOnWrite();
      instance.setImportCustomCsv(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
     */
    public Builder mergeImportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv value) {
      copyOnWrite();
      instance.mergeImportCustomCsv(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ImportCustomCsv import_custom_csv = 7;</code>
     */
    public Builder clearImportCustomCsv() {
      copyOnWrite();
      instance.clearImportCustomCsv();
      return this;
    }

    /**
     * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
     */
    @java.lang.Override
    public boolean hasExportCustomCsv() {
      return instance.hasExportCustomCsv();
    }
    /**
     * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv getExportCustomCsv() {
      return instance.getExportCustomCsv();
    }
    /**
     * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
     */
    public Builder setExportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv value) {
      copyOnWrite();
      instance.setExportCustomCsv(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
     */
    public Builder setExportCustomCsv(
        com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv.Builder builderForValue) {
      copyOnWrite();
      instance.setExportCustomCsv(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
     */
    public Builder mergeExportCustomCsv(com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv value) {
      copyOnWrite();
      instance.mergeExportCustomCsv(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ExportCustomCsv export_custom_csv = 8;</code>
     */
    public Builder clearExportCustomCsv() {
      copyOnWrite();
      instance.clearExportCustomCsv();
      return this;
    }

    /**
     * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
     */
    @java.lang.Override
    public boolean hasExportBackup() {
      return instance.hasExportBackup();
    }
    /**
     * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ExportBackup getExportBackup() {
      return instance.getExportBackup();
    }
    /**
     * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
     */
    public Builder setExportBackup(com.siansiansu.taigikeyboard.engine.proto.ExportBackup value) {
      copyOnWrite();
      instance.setExportBackup(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
     */
    public Builder setExportBackup(
        com.siansiansu.taigikeyboard.engine.proto.ExportBackup.Builder builderForValue) {
      copyOnWrite();
      instance.setExportBackup(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
     */
    public Builder mergeExportBackup(com.siansiansu.taigikeyboard.engine.proto.ExportBackup value) {
      copyOnWrite();
      instance.mergeExportBackup(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ExportBackup export_backup = 9;</code>
     */
    public Builder clearExportBackup() {
      copyOnWrite();
      instance.clearExportBackup();
      return this;
    }

    /**
     * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
     */
    @java.lang.Override
    public boolean hasImportBackup() {
      return instance.hasImportBackup();
    }
    /**
     * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ImportBackup getImportBackup() {
      return instance.getImportBackup();
    }
    /**
     * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
     */
    public Builder setImportBackup(com.siansiansu.taigikeyboard.engine.proto.ImportBackup value) {
      copyOnWrite();
      instance.setImportBackup(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
     */
    public Builder setImportBackup(
        com.siansiansu.taigikeyboard.engine.proto.ImportBackup.Builder builderForValue) {
      copyOnWrite();
      instance.setImportBackup(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
     */
    public Builder mergeImportBackup(com.siansiansu.taigikeyboard.engine.proto.ImportBackup value) {
      copyOnWrite();
      instance.mergeImportBackup(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ImportBackup import_backup = 10;</code>
     */
    public Builder clearImportBackup() {
      copyOnWrite();
      instance.clearImportBackup();
      return this;
    }

    /**
     * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
     */
    @java.lang.Override
    public boolean hasSearchCustomEntries() {
      return instance.hasSearchCustomEntries();
    }
    /**
     * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries getSearchCustomEntries() {
      return instance.getSearchCustomEntries();
    }
    /**
     * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
     */
    public Builder setSearchCustomEntries(com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries value) {
      copyOnWrite();
      instance.setSearchCustomEntries(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
     */
    public Builder setSearchCustomEntries(
        com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries.Builder builderForValue) {
      copyOnWrite();
      instance.setSearchCustomEntries(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
     */
    public Builder mergeSearchCustomEntries(com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries value) {
      copyOnWrite();
      instance.mergeSearchCustomEntries(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SearchCustomEntries search_custom_entries = 11;</code>
     */
    public Builder clearSearchCustomEntries() {
      copyOnWrite();
      instance.clearSearchCustomEntries();
      return this;
    }

    /**
     * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
     */
    @java.lang.Override
    public boolean hasListLearningRecords() {
      return instance.hasListLearningRecords();
    }
    /**
     * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords getListLearningRecords() {
      return instance.getListLearningRecords();
    }
    /**
     * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
     */
    public Builder setListLearningRecords(com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords value) {
      copyOnWrite();
      instance.setListLearningRecords(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
     */
    public Builder setListLearningRecords(
        com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords.Builder builderForValue) {
      copyOnWrite();
      instance.setListLearningRecords(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
     */
    public Builder mergeListLearningRecords(com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords value) {
      copyOnWrite();
      instance.mergeListLearningRecords(value);
      return this;
    }
    /**
     * <code>.taigi.engine.ListLearningRecords list_learning_records = 12;</code>
     */
    public Builder clearListLearningRecords() {
      copyOnWrite();
      instance.clearListLearningRecords();
      return this;
    }

    /**
     * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
     */
    @java.lang.Override
    public boolean hasSetLearningRecordCount() {
      return instance.hasSetLearningRecordCount();
    }
    /**
     * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount getSetLearningRecordCount() {
      return instance.getSetLearningRecordCount();
    }
    /**
     * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
     */
    public Builder setSetLearningRecordCount(com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount value) {
      copyOnWrite();
      instance.setSetLearningRecordCount(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
     */
    public Builder setSetLearningRecordCount(
        com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount.Builder builderForValue) {
      copyOnWrite();
      instance.setSetLearningRecordCount(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
     */
    public Builder mergeSetLearningRecordCount(com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount value) {
      copyOnWrite();
      instance.mergeSetLearningRecordCount(value);
      return this;
    }
    /**
     * <code>.taigi.engine.SetLearningRecordCount set_learning_record_count = 13;</code>
     */
    public Builder clearSetLearningRecordCount() {
      copyOnWrite();
      instance.clearSetLearningRecordCount();
      return this;
    }

    /**
     * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
     */
    @java.lang.Override
    public boolean hasDeleteLearningRecord() {
      return instance.hasDeleteLearningRecord();
    }
    /**
     * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord getDeleteLearningRecord() {
      return instance.getDeleteLearningRecord();
    }
    /**
     * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
     */
    public Builder setDeleteLearningRecord(com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord value) {
      copyOnWrite();
      instance.setDeleteLearningRecord(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
     */
    public Builder setDeleteLearningRecord(
        com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord.Builder builderForValue) {
      copyOnWrite();
      instance.setDeleteLearningRecord(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
     */
    public Builder mergeDeleteLearningRecord(com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord value) {
      copyOnWrite();
      instance.mergeDeleteLearningRecord(value);
      return this;
    }
    /**
     * <code>.taigi.engine.DeleteLearningRecord delete_learning_record = 14;</code>
     */
    public Builder clearDeleteLearningRecord() {
      copyOnWrite();
      instance.clearDeleteLearningRecord();
      return this;
    }

    /**
     * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
     */
    @java.lang.Override
    public boolean hasMoveLearningRecordToCustomDictionary() {
      return instance.hasMoveLearningRecordToCustomDictionary();
    }
    /**
     * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
     */
    @java.lang.Override
    public com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary getMoveLearningRecordToCustomDictionary() {
      return instance.getMoveLearningRecordToCustomDictionary();
    }
    /**
     * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
     */
    public Builder setMoveLearningRecordToCustomDictionary(com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary value) {
      copyOnWrite();
      instance.setMoveLearningRecordToCustomDictionary(value);
      return this;
    }
    /**
     * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
     */
    public Builder setMoveLearningRecordToCustomDictionary(
        com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary.Builder builderForValue) {
      copyOnWrite();
      instance.setMoveLearningRecordToCustomDictionary(builderForValue.build());
      return this;
    }
    /**
     * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
     */
    public Builder mergeMoveLearningRecordToCustomDictionary(com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary value) {
      copyOnWrite();
      instance.mergeMoveLearningRecordToCustomDictionary(value);
      return this;
    }
    /**
     * <code>.taigi.engine.MoveLearningRecordToCustomDictionary move_learning_record_to_custom_dictionary = 15;</code>
     */
    public Builder clearMoveLearningRecordToCustomDictionary() {
      copyOnWrite();
      instance.clearMoveLearningRecordToCustomDictionary();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:taigi.engine.UserDataRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.UserDataRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "method_",
            "methodCase_",
            com.siansiansu.taigikeyboard.engine.proto.OpenUserData.class,
            com.siansiansu.taigikeyboard.engine.proto.ResetUserData.class,
            com.siansiansu.taigikeyboard.engine.proto.RecordUsage.class,
            com.siansiansu.taigikeyboard.engine.proto.ListCustomEntries.class,
            com.siansiansu.taigikeyboard.engine.proto.SaveCustomEntry.class,
            com.siansiansu.taigikeyboard.engine.proto.DeleteCustomEntry.class,
            com.siansiansu.taigikeyboard.engine.proto.ImportCustomCsv.class,
            com.siansiansu.taigikeyboard.engine.proto.ExportCustomCsv.class,
            com.siansiansu.taigikeyboard.engine.proto.ExportBackup.class,
            com.siansiansu.taigikeyboard.engine.proto.ImportBackup.class,
            com.siansiansu.taigikeyboard.engine.proto.SearchCustomEntries.class,
            com.siansiansu.taigikeyboard.engine.proto.ListLearningRecords.class,
            com.siansiansu.taigikeyboard.engine.proto.SetLearningRecordCount.class,
            com.siansiansu.taigikeyboard.engine.proto.DeleteLearningRecord.class,
            com.siansiansu.taigikeyboard.engine.proto.MoveLearningRecordToCustomDictionary.class,
          };
          java.lang.String info =
              "\u0000\u000f\u0001\u0000\u0001\u000f\u000f\u0000\u0000\u0000\u0001<\u0000\u0002<" +
              "\u0000\u0003<\u0000\u0004<\u0000\u0005<\u0000\u0006<\u0000\u0007<\u0000\b<\u0000" +
              "\t<\u0000\n<\u0000\u000b<\u0000\f<\u0000\r<\u0000\u000e<\u0000\u000f<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.UserDataRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.UserDataRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.UserDataRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.UserDataRequest)
  private static final com.siansiansu.taigikeyboard.engine.proto.UserDataRequest DEFAULT_INSTANCE;
  static {
    UserDataRequest defaultInstance = new UserDataRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserDataRequest.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserDataRequest> PARSER;

  public static com.google.protobuf.Parser<UserDataRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
