// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user_data.proto
// Protobuf Java Version: 4.36.2

package com.siansiansu.taigikeyboard.engine.proto;

/**
 * <pre>
 * Acknowledges the open. A store that is not ready — a file from a later
 * build, a disk error — stays closed and ranks neutrally; the engine logs
 * which (`user_data.open …`). No platform read the per-store flags, so
 * they went (2026-09-30).
 * </pre>
 *
 * Protobuf type {@code taigi.engine.UserDataOpened}
 */
@com.google.protobuf.Generated
public  final class UserDataOpened extends
    com.google.protobuf.GeneratedMessageLite<
        UserDataOpened, UserDataOpened.Builder> implements
    // @@protoc_insertion_point(message_implements:taigi.engine.UserDataOpened)
    UserDataOpenedOrBuilder {
  private UserDataOpened() {
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.siansiansu.taigikeyboard.engine.proto.UserDataOpened prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Acknowledges the open. A store that is not ready — a file from a later
   * build, a disk error — stays closed and ranks neutrally; the engine logs
   * which (`user_data.open …`). No platform read the per-store flags, so
   * they went (2026-09-30).
   * </pre>
   *
   * Protobuf type {@code taigi.engine.UserDataOpened}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.siansiansu.taigikeyboard.engine.proto.UserDataOpened, Builder> implements
      // @@protoc_insertion_point(builder_implements:taigi.engine.UserDataOpened)
      com.siansiansu.taigikeyboard.engine.proto.UserDataOpenedOrBuilder {
    // Construct using com.siansiansu.taigikeyboard.engine.proto.UserDataOpened.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    // @@protoc_insertion_point(builder_scope:taigi.engine.UserDataOpened)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.siansiansu.taigikeyboard.engine.proto.UserDataOpened();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = null;
          java.lang.String info =
              "\u0000\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.siansiansu.taigikeyboard.engine.proto.UserDataOpened> parser = PARSER;
        if (parser == null) {
          synchronized (com.siansiansu.taigikeyboard.engine.proto.UserDataOpened.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.siansiansu.taigikeyboard.engine.proto.UserDataOpened>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:taigi.engine.UserDataOpened)
  private static final com.siansiansu.taigikeyboard.engine.proto.UserDataOpened DEFAULT_INSTANCE;
  static {
    UserDataOpened defaultInstance = new UserDataOpened();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserDataOpened.class, defaultInstance);
  }

  public static com.siansiansu.taigikeyboard.engine.proto.UserDataOpened getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserDataOpened> PARSER;

  public static com.google.protobuf.Parser<UserDataOpened> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
